### ISSUE TITLE
pip install libvirt-python-4.4.0 failed.

### ISSUE THREAD

**Issue by jb-alvarado** [jeffreywildman/homebrew-virt-manager#101]
Hello,
I remove virt-manager and wanted to reinstall it again, but now it fails with:

```
==> Installing virt-manager from jeffreywildman/virt-manager
==> Downloading https://virt-manager.org/download/sources/virt-manager/virt-manager-1.5.1.tar.gz
==> Downloading from https://releases.pagure.org/virt-manager/virt-manager-1.5.1.tar.gz
######################################################################## 100.0%
==> Patching
patching file virt-manager
==> Downloading https://files.pythonhosted.org/packages/33/bc/fa0b5347139cd9564f0d44ebd2b147ac97c36b2403943dbee8a25fd74012/virtualenv-16.0.0.tar.gz
Already downloaded: /Users/jb_/Library/Caches/Homebrew/virt-manager--homebrew-virtualenv-16.0.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/virt-manager--homebrew-virtualenv-20180703-49866-ir96j0/target --single-version-externally-managed --record=installed.txt
==> python -s /private/tmp/virt-manager--homebrew-virtualenv-20180703-49866-ir96j0/target/bin/virtualenv -p python /usr/local/Cellar/virt-manager/1.5.1/libexec
==> Downloading https://libvirt.org/sources/python/libvirt-python-4.4.0.tar.gz
Already downloaded: /Users/jb_/Library/Caches/Homebrew/virt-manager--libvirt-python-4.4.0.tar.gz
==> /usr/local/Cellar/virt-manager/1.5.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/virt-manager--libvirt-python-20180703-49866-1hgcpih/libvirt-python-4.4.0
Last 15 lines from /Users/jb_/Library/Logs/Homebrew/virt-manager/03.pip:
  Removing source in /private/tmp/pip-req-build-JEsZdU
Command "/usr/local/Cellar/virt-manager/1.5.1/libexec/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-JEsZdU/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-HIYsKb/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/1.5.1/libexec/bin/../include/site/python2.7/libvirt-python" failed with error code 1 in /private/tmp/pip-req-build-JEsZdU/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/1.5.1/libexec/lib/python2.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/virt-manager/1.5.1/libexec/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/usr/local/Cellar/virt-manager/1.5.1/libexec/lib/python2.7/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/local/Cellar/virt-manager/1.5.1/libexec/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 779, in install
    spinner=spinner,
  File "/usr/local/Cellar/virt-manager/1.5.1/libexec/lib/python2.7/site-packages/pip/_internal/utils/misc.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/local/Cellar/virt-manager/1.5.1/libexec/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-JEsZdU/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-HIYsKb/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/1.5.1/libexec/bin/../include/site/python2.7/libvirt-python" failed with error code 1 in /private/tmp/pip-req-build-JEsZdU/
```
Is almost the same problem then here #98, but the fix wont work for me.

**Comment by volunteeer** [comment]
Have the same issue. Any suggestions?

**Comment by OloBo-MSK** [comment]
brew edit virt-manager
change libvirt-python-4.4.0 > libvirt-python-4.5.0
SHA256 > "ef35ed6bc24d76563b1ba9b068ef5a048016726dba62a9d057fe6dfbea6b0f60"
save
run install again

Works for me.

**Comment by volunteeer** [comment]
Thanks, works just fine!

**Comment by jb-alvarado** [comment]
Thank you! That works for me to!
