### ISSUE TITLE
Failure to compile libvirt-glib on Mac OS 10.13.5

### ISSUE THREAD

**Issue by dostoevskylabs** [jeffreywildman/homebrew-virt-manager#102]
Hello guys,

First let me start by saying I've read the past 20 or so issues and I have taken special note to make sure that the version in the virt-manager.rb file for python-libvirt matches the version of libvirt installed by brew (currently 4.50) (you can see the repo in my repository for the fork)

However, I'm still running into the same issue, is there anyone who is currently running this on 10.13.5 who can provide a glimmer of hope.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/gobject-introspection/1.56.1/bin/g-ir-scanner", line 66, in <module>
    sys.exit(scanner_main(sys.argv))
  File "/usr/local/Cellar/gobject-introspection/1.56.1/lib/gobject-introspection/giscanner/scannermain.py", line 538, in scanner_main
    ss = create_source_scanner(options, args)
  File "/usr/local/Cellar/gobject-introspection/1.56.1/lib/gobject-introspection/giscanner/scannermain.py", line 446, in create_source_scanner
    ss.parse_files(filenames)
  File "/usr/local/Cellar/gobject-introspection/1.56.1/lib/gobject-introspection/giscanner/sourcescanner.py", line 263, in parse_files
    self._parse(headers)
  File "/usr/local/Cellar/gobject-introspection/1.56.1/lib/gobject-introspection/giscanner/sourcescanner.py", line 308, in _parse
    self._cpp_options)
  File "/usr/local/Cellar/gobject-introspection/1.56.1/lib/gobject-introspection/giscanner/ccompiler.py", line 210, in preprocess
    extra_postargs=extra_postargs)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/unixccompiler.py", line 113, in preprocess
    raise CompileError, msg
distutils.errors.CompileError: command 'clang' terminated by signal 10
make[1]: *** [LibvirtGLib-1.0.gir] Error 1
make: *** [install-recursive] Error 1
```

Homebrew info
```
HOMEBREW_VERSION: 1.6.9-123-g4840b68
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4840b688e042d5db38f53a99ef64650ffac43693
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 07928a16f14b94d2574553eec82c6fa7b5a2f387
Core tap last commit: 17 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CACHE: /Users/dostoevsky/Library/Caches/Homebrew
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.5-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: N/A
XQuartz: N/A
```

I'd also note this is on a fairly fresh install of MacOS and upgrading to High Sierra from 10.11. I don't doubt that it's environmental but none of the previously mentioned things are related. Any clues would be greatly appreciated, thank you for all the work and effort you have put into this!

Update:
If I remove the introspection flags from the configure calls it will build everything (but i understand it wont build correctly), but then it will result in this error:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/1.5.1/libexec/share/virt-manager/virt-manager", line 32, in <module>
    gi.require_version('LibvirtGLib', '1.0')
  File "/usr/local/opt/pygobject3/lib/python2.7/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace LibvirtGLib not available
```

I believe the root cause can be attributed to the gobject package, during install I notice that it is installing bindings for python2 and python3 as per the virt-manager.rb file call.

So I guess my issue is that I can't seem to use that package? I'm not sure.

**Comment by dostoevskylabs** [comment]
I thought i figured it out when reading a similar issue on github, but it ended up not being a solution either. Reopening the issue in hopes of getting it figured out, thanks.

**Comment by dostoevskylabs** [comment]
dunno what happened, but i tried again today and it just worked. thanks.. lol.
