### ISSUE TITLE
"ModuleNotFoundError: No module named 'cygvirtmod'"

### ISSUE THREAD

**Issue by hit0wnzzz** [jeffreywildman/homebrew-virt-manager#119]
OS X Mojave - 10.14.3

`
$ virt-manager 
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.0.0_1/libexec/lib/python3.7/site-packages/libvirt.py", line 24, in <module>
    import cygvirtmod as libvirtmod
ModuleNotFoundError: No module named 'cygvirtmod'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.0.0_1/libexec/share/virt-manager/virt-manager", line 20, in <module>
    from virtinst import util
  File "/usr/local/Cellar/virt-manager/2.0.0_1/libexec/share/virt-manager/virtinst/__init__.py", line 26, in <module>
    from virtinst import util
  File "/usr/local/Cellar/virt-manager/2.0.0_1/libexec/share/virt-manager/virtinst/util.py", line 15, in <module>
    import libvirt
  File "/usr/local/Cellar/virt-manager/2.0.0_1/libexec/lib/python3.7/site-packages/libvirt.py", line 28, in <module>
    raise lib_e
  File "/usr/local/Cellar/virt-manager/2.0.0_1/libexec/lib/python3.7/site-packages/libvirt.py", line 20, in <module>
    import libvirtmod
ImportError: dlopen(/usr/local/Cellar/virt-manager/2.0.0_1/libexec/lib/python3.7/site-packages/libvirtmod.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/libidn2/lib/libidn2.0.dylib
  Referenced from: /usr/local/opt/gnutls/lib/libgnutls.30.dylib
  Reason: image not found
Tetradecahedron:~ rawco$ pip install cygvirtmod
Collecting cygvirtmod
  Could not find a version that satisfies the requirement cygvirtmod (from versions: )
No matching distribution found for cygvirtmod
Tetradecahedron:~ rawco$ pip3 install cygvirtmod
Collecting cygvirtmod
  Could not find a version that satisfies the requirement cygvirtmod (from versions: )
No matching distribution found for cygvirtmod
`

**Comment by jeffreywildman** [comment]
It's possible that this is caused by a mismatch of `libvirt` and `libvirt-python`. Both are currently at 5.6.0 in the `libvirt` and `virt-manager` formulae -- is this still an issue?

**Comment by tbrtje** [comment]
yes it still occurs.

**Comment by Lau-San** [comment]
I'm getting this error as well, any updates?

**Comment by Greatz08** [comment]
i am also getting same error :-((
