### ISSUE TITLE
pci.ids: No Such File Or Directory

### ISSUE THREAD

**Issue by Selora** [jeffreywildman/homebrew-virt-manager#140]
Hi,

I'm getting this error when trying to open a VM (right-click->open or doubleclick).
This only started to happen after a full brew upgrade today, not sure what broke.

```Error launching details: g-io-error-quark: Error opening file /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/pci.ids: No such file or directory (1)```

Apologies for this half-assed bug report, I'm just at lost as to where to start to debug this. This seems to be `libosinfo` that fails to create the pci.ids file properly. I tried reinstalling `libosinfo` and `virt-manager` but I'm not getting any further.

**Comment by superlazycoder** [comment]
I "Literally" just ran into this issue.
I solved it by replacing the files.

create and open the folder in question.
```
mkdir -p /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/
cd /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/
open .

```

pci.ids is located at the following url
https://pci-ids.ucw.cz/

usb.ids is located at the following url
http://www.linux-usb.org/usb-ids.html


After replacing these files manually the viewer works.

**Comment by Selora** [comment]
Yup it works! Thanks! 
Looks like there was some changes [here](https://gitlab.com/libosinfo/libosinfo/commit/1246a55a94e5ee0dd9155e53c70b2f52e454565d) recently, maybe that's what broke everything? There's some outdated dependencies in this homebrew packages too.  
Anyway, easy enough fix that I'm not bothering digging any deeper

**Comment by gearboxscott** [comment]
I did a reinstall of my whole brew on Catalina.  I get this error:

```Error launching details: g-io-error-quark: Error opening file /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/pci.ids: No such file or directory (1)

Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtManager/vmwindow.py", line 39, in get_instance
    cls._instances[key] = vmmVMWindow(vm)
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtManager/vmwindow.py", line 77, in __init__
    self.is_customize_dialog)
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtManager/details/details.py", line 447, in __init__
    self.init_details()
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtManager/details/details.py", line 774, in init_details
    self._os_list = vmmOSList()
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtManager/oslist.py", line 39, in __init__
    self._init_state()
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtManager/oslist.py", line 55, in _init_state
    all_os = virtinst.OSDB.list_os()
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtinst/osdict.py", line 274, in list_os
    for name, osobj in self._all_variants.items():
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtinst/osdict.py", line 198, in _all_variants
    loader = self._os_loader
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtinst/osdict.py", line 190, in _os_loader
    loader.process_default_path()
gi.repository.GLib.GError: g-io-error-quark: Error opening file /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/pci.ids: No such file or directory (1)```

then I followed the steps above for adding the ids and get a new error:

```Error launching details: libosinfo: Incorrect root element (0)

Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtManager/vmwindow.py", line 39, in get_instance
    cls._instances[key] = vmmVMWindow(vm)
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtManager/vmwindow.py", line 77, in __init__
    self.is_customize_dialog)
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtManager/details/details.py", line 447, in __init__
    self.init_details()
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtManager/details/details.py", line 774, in init_details
    self._os_list = vmmOSList()
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtManager/oslist.py", line 39, in __init__
    self._init_state()
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtManager/oslist.py", line 55, in _init_state
    all_os = virtinst.OSDB.list_os()
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtinst/osdict.py", line 274, in list_os
    for name, osobj in self._all_variants.items():
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtinst/osdict.py", line 198, in _all_variants
    loader = self._os_loader
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtinst/osdict.py", line 190, in _os_loader
    loader.process_default_path()
gi.repository.GLib.GError: libosinfo: Incorrect root element (0)```

In addition the command line is spewing out this information:

```
virt-manager
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtManager/manager.py", line 474, in show_vm
    vmmenu.VMActionUI.show(self, self.current_vm())
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtManager/vmmenu.py", line 330, in show
    vmmVMWindow.get_instance(src, vm).show()
AttributeError: 'NoneType' object has no attribute 'show'
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtManager/manager.py", line 489, in row_activated
    self.show_vm(_src)
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtManager/manager.py", line 474, in show_vm
    vmmenu.VMActionUI.show(self, self.current_vm())
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtManager/vmmenu.py", line 330, in show
    vmmVMWindow.get_instance(src, vm).show()
AttributeError: 'NoneType' object has no attribute 'show'

** (virt-manager:74693): WARNING **: 12:35:41.519: Entity http://fedoraproject.org/fedora/rawhide must be in file os/fedoraproject.org/fedora-rawhide.xml not tests/data/positive/os/fedoraproject.org/fedora-rawhide.xml

** (virt-manager:74693): WARNING **: 12:35:41.643: Entity http://ibm.com/ps2/keyboard must be in file device/ibm.com/ps2-keyboard.xml not tests/data/positive/device/ibm.com/ps2-keyboard.xml

** (virt-manager:74693): WARNING **: 12:35:41.650: Entity http://fedoraproject.org/fedora/rawhide must be in file os/fedoraproject.org/fedora-rawhide.xml not tests/data/negative/os/fedoraproject.org/fedora-rawhide.xml

** (virt-manager:74693): WARNING **: 12:35:41.685: Entity http://linux-kvm.org/qemu-kvm/1.2.0 must be in file platform/linux-kvm.org/qemu-kvm-1.2.0.xml not tests/data/positive/platform/linux-kvm.org/qemu-kvm-1.2.0.xml

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://redhat.com/rhel/7.6 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://fedoraproject.org/silverblue/28 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://redhat.com/rhel/6.0 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://redhat.com/rhel/7.7 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://redhat.com/rhel/6.1 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://dragonflybsd.org/dragonflybsd/4.2.4 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://freebsd.org/freebsd/1.0 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://opensuse.org/opensuse/tumbleweed referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://debian.org/debian/3 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://mandriva.com/mandrake/7.2 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://redhat.com/rhel/6.2 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://dragonflybsd.org/dragonflybsd/2.4.1 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://netbsd.org/netbsd/0.9 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://xen.org/xen/3.3.0 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://redhat.com/rhl/2.1 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://microsoft.com/win/3.1 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://microsoft.com/windows/sif/desktop referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://redhat.com/rhel/2.1 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://redhat.com/rhel/6.3 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://freebsd.org/freebsd/5.5 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://ubuntu.com/ubuntu/13.04 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://redhat.com/rhel/6.4 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://dragonflybsd.org/dragonflybsd/2.0.1 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://xen.org/xen/3.3.2 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://debian.org/debian/1.3 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://freebsd.org/freebsd/8.2 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://redhat.com/rhel/6.5 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://redhat.com/rhl/7 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://scientificlinux.org/scientificlinux/7.6 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://dragonflybsd.org/dragonflybsd/3.6.2 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://ubuntu.com/ubuntu/12.04 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://qemu.org/qemu/1.4.1 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://redhat.com/rhel/6.6 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://microsoft.com/win/8/l10n-language-reverse referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.725: Entity http://redhat.com/rhel/6.10 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://altlinux.org/alt/8.2 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://dragonflybsd.org/dragonflybsd/3.2.1 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://opensuse.org/opensuse/10.3 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://ubuntu.com/ubuntu/15.10 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://altlinux.org/altlinux/6.0 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://redhat.com/rhl/5.1 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://redhat.com/rhel/6.7 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://dragonflybsd.org/dragonflybsd/2.10.1 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://suse.com/sle/15 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://redhat.com/rhel/5.10 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://redhat.com/rhel/6.8 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://qemu.org/qemu/1.1 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://redhat.com/rhel/5.11 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://mandriva.com/mandriva/2010.1 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://redhat.com/rhel/6.9 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://suse.com/sle/15-unknown referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://ubuntu.com/ubuntu/preseed/desktop referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://dragonflybsd.org/dragonflybsd/1.10.1 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://sun.com/solaris/9 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://qemu.org/chipset/x86/q35 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://microsoft.com/windows/cmd/desktop referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://microsoft.com/win/2k3r2 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://qemu.org/qemu/1.7.2 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://cirros-cloud.net/cirros/0.3.5 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://freebsd.org/freebsd/3.0 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://endlessos.com/eos/3.5 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://microsoft.com/windows/reg/desktop referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://mandriva.com/mandriva/2007.1 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://opensuse.org/opensuse/42.3 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://ubuntu.com/ubuntu/7.04 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://microsoft.com/windows/unattend/desktop referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://suse.com/sles/12.4 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://altlinux.org/altlinux/2.4 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://redhat.com/rhel/kickstart/desktop referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://dragonflybsd.org/dragonflybsd/5.2.2 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://dragonflybsd.org/dragonflybsd/1.4.4 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://fedoraproject.org/fedora/18 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://dragonflybsd.org/dragonflybsd/1.0A referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://freebsd.org/freebsd/4.9 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://netbsd.org/netbsd/4.0 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://opensuse.org/opensuse/autoyast/desktop referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://microsoft.com/win/1.0 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://fedoraproject.org/fedora/19 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://redhat.com/rhel/8-unknown referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://ubuntu.com/ubuntu/9.10 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://freebsd.org/freebsd/11.2 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://ubuntu.com/ubuntu/6.06 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://netbsd.org/netbsd/1.6 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://redhat.com/rhel/7.0 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://system76.com/popos/17.10 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://microsoft.com/win/8.1 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://qemu.org/qemu/1.2.0 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://redhat.com/rhel/7.1 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://mandriva.com/mandriva/2006.0 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://ubuntu.com/ubuntu/18.04 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://redhat.com/rhel/7.2 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://xen.org/xen/vbd referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://suse.com/sled/10 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://netbsd.org/netbsd/7.1 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://linux-kvm.org/qemu-kvm/1.1.2 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://redhat.com/rhel/kickstart/jeos referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://redhat.com/rhl/7.3 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://suse.com/sles/11.4 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://redhat.com/rhel/7.3 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://dragonflybsd.org/dragonflybsd/4.6.2 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://suse.com/sled/11 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://freebsd.org/freebsd/10.0 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://redhat.com/rhel/7.4 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://suse.com/sles/9 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://microsoft.com/winnt/3.5 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://suse.com/caasp/2.0 referenced but not defined

** (virt-manager:74693): WARNING **: 12:35:41.726: Entity http://redhat.com/rhel/7.5 referenced but not defined
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtManager/manager.py", line 489, in row_activated
    self.show_vm(_src)
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtManager/manager.py", line 474, in show_vm
    vmmenu.VMActionUI.show(self, self.current_vm())
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/share/virt-manager/virtManager/vmmenu.py", line 330, in show
    vmmVMWindow.get_instance(src, vm).show()
AttributeError: 'NoneType' object has no attribute 'show'
```

not sure where to fix this?

**Comment by gearboxscott** [comment]
other info:

```brew info virt-manager
jeffreywildman/virt-manager/virt-manager: stable 2.2.1
App for managing virtual machines
https://virt-manager.org/
/usr/local/Cellar/virt-manager/2.2.1_2 (1,685 files, 22.2MB) *
  Built from source on 2019-12-13 at 12:30:35
From: https://github.com/jeffreywildman/homebrew-virt-manager/blob/master/virt-manager.rb
==> Dependencies
Build: intltool ✔, pkg-config ✔
Required: adwaita-icon-theme ✔, gtk+3 ✔, gtk-vnc ✔, gtksourceview4 ✔, hicolor-icon-theme ✔, libosinfo ✔, libvirt ✔, libvirt-glib ✔, libxml2 ✔, osinfo-db ✔, py3cairo ✔, pygobject3 ✔, python ✔, spice-gtk ✔, vte3 ✔
```

**Comment by avindra** [comment]
Thanks for the info folks, seeing this issue in Linux as well.

Of note, Red Hat has deprecated `virt-manager` in their 8.1 release

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.1_release_notes/deprecated_functionality#deprecated-functionality_virtualization

The shift is towards [Cockpit](https://cockpit-project.org/), which is a web-based interface to manage machines. It has features for containers also. I myself have not tried it yet, but hopefully it has near-complete feature parity with `virt-manager`, particularly in configuring the machines.

`virt-manager` has a lot of built-in validations to prevent selection of invalid / incompatible VM settings, which saves a lot of time.

**Comment by avindra** [comment]
Another finding, I'm able to see the files in :

```
$ ls /usr/share/hwdata/
iab.txt  oui.txt  pci.ids  pnp.ids  usb.ids
```

which is owned by the `hwdata` package. Seems like this issue is relatively easy, just not sure which package it's broken in

**Comment by peschmae** [comment]
I was able to workaround this issue, with switching the active libosinfo back to 1.6.0 (which I had installed previously), so it's definitely related to the update of libosinfo

**Comment by jackcarrozzo** [comment]
Same thing here, using `virt-manager` via brew on OSX. Solve with
`cp -R /usr/local/Cellar/libosinfo/1.6.0/share/libosinfo /usr/local/Cellar/libosinfo/1.7.1/share/`

My vers:

````libosinfo: stable 1.7.1 (bottled)
The Operating System information database
https://libosinfo.org/
/usr/local/Cellar/libosinfo/1.6.0 (213 files, 4.7MB)
  Poured from bottle on 2019-10-22 at 10:26:29
/usr/local/Cellar/libosinfo/1.7.1 (161 files, 3.7MB) *
  Poured from bottle on 2020-02-25 at 11:30:12
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libosinfo.rb
==> Dependencies
Build: gobject-introspection ✔, meson ✘, ninja ✘, pkg-config ✔
Required: check ✔, gettext ✔, glib ✘, libsoup ✘, libxml2 ✔````

**Comment by mld** [comment]
> ```
> mkdir -p /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/
> cd /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/
> open .
> ```
> 
> now you can download from the following locations, and drag/drop them into this new folder
> 
> pci.ids is located at the following url
> https://pci-ids.ucw.cz/
> 
> usb.ids is located at the following url
> http://www.linux-usb.org/usb-ids.html
> 
> After replacing these files manually the viewer works.

Even easier:

```
mkdir /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo
wget http://www.linux-usb.org/usb.ids -O /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/usb.ids
wget https://pci-ids.ucw.cz/v2.2/pci.ids -O /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/pci.ids
```

**Comment by angryhamsterx** [comment]
More right urls (from libosinfo sources):
```
mkdir -p /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo
wget -O /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/usb.ids "http://www.linux-usb.org/usb.ids"
wget -O /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/pci.ids "http://pciids.sourceforge.net/v2.2/pci.ids"
```

**Comment by AlbusaOxyuranus** [comment]
> > ```
> > mkdir -p /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/
> > cd /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/
> > open .
> > ```
> > 
> > 
> > now you can download from the following locations, and drag/drop them into this new folder
> > pci.ids is located at the following url
> > https://pci-ids.ucw.cz/
> > usb.ids is located at the following url
> > http://www.linux-usb.org/usb-ids.html
> > After replacing these files manually the viewer works.
> 
> 
> Even easier:
> 
> 
> ```
> mkdir /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo
> wget http://www.linux-usb.org/usb.ids -O /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/usb.ids
> wget https://pci-ids.ucw.cz/v2.2/pci.ids -O /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/pci.ids
> ```

it works. It helped me

**Comment by bdunncompany** [comment]
> I "Literally" just ran into this issue.
> I solved it by replacing the files.
> 
> create and open the folder in question.
> 
> ```
> mkdir -p /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/
> cd /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/
> open .
> ```
> 
> now you can download from the following locations, and drag/drop them into this new folder
> 
> pci.ids is located at the following url
> https://pci-ids.ucw.cz/
> 
> usb.ids is located at the following url
> http://www.linux-usb.org/usb-ids.html
> 
> After replacing these files manually the viewer works.

This worked perfectly. Thanks for saving me SOOOO much time trying to work this out on my own.

**Comment by trilom** [comment]
ywac (your words as code)
```bash
wget https://pci-ids.ucw.cz/v2.2/pci.ids -O /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/pci.ids
wget http://www.linux-usb.org/usb.ids -O /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/usb.ids
```

**Comment by cjntaylor** [comment]
Version independent ywac:
```bash
mkdir -p $(brew --prefix libosinfo)/share/libosinfo
wget https://pci-ids.ucw.cz/v2.2/pci.ids -O $(brew --prefix libosinfo)/share/libosinfo/pci.ids
wget http://www.linux-usb.org/usb.ids -O $(brew --prefix libosinfo)/share/libosinfo/usb.ids
```

**Comment by peschmae** [comment]
Ran into the same issue again, after a brew upgrade, my solution was to downgrad libosinfo to version 1.6.0 (which sadly isn't a versioned formula), using the git commit.

```
brew unlink libosinfo
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/44410d3ec00d88e7c6afa362ebc50176dfc75157/Formula/libosinfo.rb
brew pin libosinfo
```

Still not entirely sure, if this is something that needs to be fixed in this formulae,  or if the libosinfo formulae is broken

**Comment by jouve** [comment]
https://github.com/Homebrew/homebrew-core/pull/58285

**Comment by jouve** [comment]
fixed in homebrew-core (1.8.0_1)

**Comment by gearboxscott** [comment]
I tried it out, now I'm getting:

```
Error launching create dialog: libosinfo: Incorrect root element (0)

Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtManager/createvm.py", line 111, in show_instance
    cls._instance = vmmCreateVM()
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtManager/createvm.py", line 188, in __init__
    self._init_state()
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtManager/createvm.py", line 324, in _init_state
    self._os_list = vmmOSList()
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtManager/oslist.py", line 39, in __init__
    self._init_state()
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtManager/oslist.py", line 55, in _init_state
    all_os = virtinst.OSDB.list_os()
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtinst/osdict.py", line 274, in list_os
    for name, osobj in self._all_variants.items():
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtinst/osdict.py", line 198, in _all_variants
    loader = self._os_loader
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtinst/osdict.py", line 190, in _os_loader
    loader.process_default_path()
gi.repository.GLib.GError: libosinfo: Incorrect root element (0)```

so the file issue is gone but element (0) has surfaced.

**Comment by jouve** [comment]
maybe reinstall osinfo-db ?

**Comment by gearboxscott** [comment]
Actually, I have been uninstalling brew and reinstalling it.  I don't use brew for much else except autojump.  So yesterday, I removed brew and reinstalled it.  Still got the error.

Scott
