### ISSUE TITLE
Error installing virt-manager

### ISSUE THREAD

**Issue by q5616417** [jeffreywildman/homebrew-virt-manager#145]
Hi,
when I try to install virt-manager, this error occurs:

==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/virt-manager--homebrew-virtualenv-20200304-452-izouvx/target --install-scripts=/private/tmp/virt-manager--homebrew-virtual
==> python3 -s /private/tmp/virt-manager--homebrew-virtualenv-20200304-452-izouvx/target/bin/virtualenv -p python3 /usr/local/Cellar/virt-manager/2.2.1_3/libexec
Error: An exception occurred within a child process:
  NameError: undefined local variable or method `python' for #<Language::Python::Virtualenv::Virtualenv:0x00007ff56ca86088>
Did you mean?  @python

Command Line Tools are 11.4 beta 3
XCode 11.3.1
MacOS 10.15.3

Do you have an idea what I could do to make virt-manager install?

Best regards

Thomas

**Comment by SithSense** [comment]
@q5616417 check to make sure your virtual environment is not activated when installing virt-manager.

**Comment by lingyunrh** [comment]
➜  ~ brew install virt-manager virt-viewer
Updating Homebrew...
==> Installing virt-manager from jeffreywildman/virt-manager
==> Downloading https://virt-manager.org/download/sources/virt-manager/virt-manager-2.2.1.tar.gz
Already downloaded: /Users/songhongcheng/Library/Caches/Homebrew/downloads/77e22463a35b2e2bde8d02253c10129aabb1e5dfbfe2e6f33ef87bd35955dcf2--virt-manager-2.2.1.tar.gz
==> Patching
patching file virt-manager
Hunk #1 succeeded at 170 (offset 19 lines).
==> Downloading https://files.pythonhosted.org/packages/11/74/2c151a13ef41ab9fb43b3c4ff9e788e0496ed7923b2078d42cab30622bdf/virtualenv-16.7.4.tar.gz
Already downloaded: /Users/songhongcheng/Library/Caches/Homebrew/downloads/507d2087bf24df82641b681a5fe4da778ef50ebe819a86ea1b584f70788f0f63--virtualenv-16.7.4.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/virt-manager--homebrew-virtualenv-20200319-39259-a8oe5x/target --install-scripts=/private/t
==> python3 -s /private/tmp/virt-manager--homebrew-virtualenv-20200319-39259-a8oe5x/target/bin/virtualenv -p python3 /usr/local/Cellar/virt-manager/2.2.1_3/libexec
Last 15 lines from /Users/songhongcheng/Library/Logs/Homebrew/virt-manager/02.python3:
Traceback (most recent call last):
  File "/private/tmp/virt-manager--homebrew-virtualenv-20200319-39259-a8oe5x/target/lib/python3.7/site-packages/virtualenv.py", line 2632, in <module>
    main()
  File "/private/tmp/virt-manager--homebrew-virtualenv-20200319-39259-a8oe5x/target/lib/python3.7/site-packages/virtualenv.py", line 870, in main
    symlink=options.symlink,
  File "/private/tmp/virt-manager--homebrew-virtualenv-20200319-39259-a8oe5x/target/lib/python3.7/site-packages/virtualenv.py", line 1173, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/private/tmp/virt-manager--homebrew-virtualenv-20200319-39259-a8oe5x/target/lib/python3.7/site-packages/virtualenv.py", line 1019, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/private/tmp/virt-manager--homebrew-virtualenv-20200319-39259-a8oe5x/target/lib/python3.7/site-packages/virtualenv.py", line 1110, in _install_wheel_with_search_dir
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=script)
  File "/private/tmp/virt-manager--homebrew-virtualenv-20200319-39259-a8oe5x/target/lib/python3.7/site-packages/virtualenv.py", line 963, in call_subprocess
    raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode))
OSError: Command /usr/local/Cellar/vi...ibexec/bin/python3.7 - setuptools pip wheel failed with error code 1
Running virtualenv with interpreter /usr/local/opt/python/bin/python3

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/jeffreywildman/homebrew-virt-manager/issues
