### ISSUE TITLE
End of file while reading data: Ncat: No such file or directory.: Input/output error

### ISSUE THREAD

**Issue by Billygoat32** [jeffreywildman/homebrew-virt-manager#147]
After performing a brew upgrade, I now get this error any time I try and connect to a remote server:

`Unable to connect to libvirt qemu+ssh://root@192.168.1.5/system.

End of file while reading data: nc: unix connect failed: No such file or directory: Input/output error

Verify that the 'libvirtd' daemon is running on the remote host.

Libvirt URI is: qemu+ssh://root@192.168.1.5/system

Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtManager/connection.py", line 956, in _do_open
    self._backend.open(connectauth.creds_dialog, self)
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtinst/connection.py", line 174, in open
    open_flags)
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/lib/python3.7/site-packages/libvirt.py", line 104, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirt.libvirtError: End of file while reading data: nc: unix connect failed: No such file or directory: Input/output error`

I have nc (netcat) installed on my local host and remote host.   There no firewalls in place - it used to "just work'™

**Comment by Billygoat32** [comment]
Interesting... trying to add the host through the UI I get the above error.  Using this command adds it and works for future connection:
virt-manager -c 'qemu+ssh://user@libvirthost/system?socket=/var/run/libvirt/libvirt-sock'

**Comment by Jamdoog** [comment]
Hello,
Using Manjaro / Arch as my host system, this error can be fixed by installing the openbsd-netcat as opposed to gnu-netcat.

**Comment by pwestrich** [comment]
I too am experiencing this issue. My libvirt host is running Ubuntu 18.04.

Using netcat-openbsd yields this error. Manually specifying the socket location (/var/run/libvirt/libvirt-sock) does not change the result:
```
Unable to connect to libvirt qemu+ssh://user@host/system.

End of file while reading data: nc: unix connect failed: No such file or directory: Input/output error

Verify that the 'libvirtd' daemon is running on the remote host.

Libvirt URI is: qemu+ssh://user@host/system

Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtManager/connection.py", line 956, in _do_open
    self._backend.open(connectauth.creds_dialog, self)
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtinst/connection.py", line 172, in open
    conn = libvirt.openAuth(self._open_uri,
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/lib/python3.8/site-packages/libvirt.py", line 104, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirt.libvirtError: End of file while reading data: nc: unix connect failed: No such file or directory: Input/output error
```

Forcing it to use netcat-traditional (via update-alternatives) yields a different error:
```
Unable to connect to libvirt qemu+ssh://user@host/system.

The remote host requires a version of netcat/nc which supports the -U option.

Libvirt URI is: qemu+ssh://user@host/system

Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtManager/connection.py", line 956, in _do_open
    self._backend.open(connectauth.creds_dialog, self)
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtinst/connection.py", line 172, in open
    conn = libvirt.openAuth(self._open_uri,
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/lib/python3.8/site-packages/libvirt.py", line 104, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirt.libvirtError: End of file while reading data: nc: invalid option -- 'U'
nc -h for help: Input/output error
```

The libvirtd service is running and alive on the server. I connected to this same host the other day from another Ubuntu machine with virt-manager and it worked fine.

**Comment by larssb** [comment]
I also have this issue. Where the facts are as follows:

* it's libvirt underneath the oVirt platform
* virsh is v6.9.0 (from this homebrew-virt-manager brew formulae)
* I'm on MacOS Big Sur v11.0.1

# Debug

1. connecting from CentOS v8 oVirt host 'A' to CentOS v8 oVirt host 'B' works
2. connecting to ///system works
3. tried installing *nmap* via *brew*
4. tried with the `?socket=/var/run/libvirt/libvirt-sock` option to *virsh*

The error I get on *virt-manager* is (used to get the debug log)

```
Mon, 16 Nov 2020 12:04:46 virt-manager 4799] DEBUG (connectauth:152) connect_error: conn transport=ssh
[Mon, 16 Nov 2020 12:04:46 virt-manager 4799] DEBUG (connection:532) conn=qemu+ssh://USER@IP/system?authfile=/etc/ovirt-hosted-engine/virsh_auth.conf?socket=/var/run/libvirt/libvirt-sock changed to state=Disconnected
[Mon, 16 Nov 2020 12:04:46 virt-manager 4799] DEBUG (engine:553) Removing failed uri=qemu+ssh://USER@IP/system?authfile=/etc/ovirt-hosted-engine/virsh_auth.conf?socket=/var/run/libvirt/libvirt-sock
[Mon, 16 Nov 2020 12:04:46 virt-manager 4799] DEBUG (error:84) error dialog message:
summary=Unable to connect to libvirt qemu+ssh://USER@IP/system?authfile=/etc/ovirt-hosted-engine/virsh_auth.conf?socket=/var/run/libvirt/libvirt-sock.

End of file while reading data: Ncat: No such file or directory.: Input/output error

Verify that the 'libvirtd' daemon is running on the remote host.
details=Libvirt URI is: qemu+ssh://USER@IP/system?authfile=/etc/ovirt-hosted-engine/virsh_auth.conf?socket=/var/run/libvirt/libvirt-sock

Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtManager/connection.py", line 956, in _do_open
    self._backend.open(connectauth.creds_dialog, self)
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtinst/connection.py", line 172, in open
    conn = libvirt.openAuth(self._open_uri,
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/lib/python3.9/site-packages/libvirt.py", line 104, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirt.libvirtError: End of file while reading data: Ncat: No such file or directory.: Input/output error
Segmentation fault: 11
```

Someone with a suggestion?

Thank you

**Comment by mbreevoort** [comment]
> Interesting... trying to add the host through the UI I get the above error. Using this command adds it and works for future connection:
> virt-manager -c 'qemu+ssh://user@libvirthost/system?socket=/var/run/libvirt/libvirt-sock'

With the above socket got the same error `End of file while reading data: Ncat: No such file or directory.: Input/output error`
When I login on the server I saw I have no rights to read the `libvirt-sock` but there is also a `libvirt-sock-ro`
Using the `libvirt-sock-ro` socket solved my problem:
`virt-manager -c 'qemu+ssh://user@libvirthost/system?socket=/var/run/libvirt/libvirt-sock-ro'`

**Comment by doughadfield** [comment]
I have the same problem and unfortunately none of the above work for me. I'm trying to connect from macos catalina to a debian server as the kvm host. The debian server has netcat-openbsd installed. I get the same error whether I try with virt-manager gui or either of the command line options above (libvirt-sock or libvirt-sock-ro). Does anyone have any other ideas, as I'd dearly love to get virt-manager working!

**Comment by landswim** [comment]
same issue on ubuntu 20.04.1 lts

**Comment by mbreevoort** [comment]
Does virt-viewer work with the libvirt-sock-ro?

**Comment by rob-scheepens** [comment]
Still happening on Monterey.

**Comment by choricc** [comment]
same issue on Anolis 8.6
