### ISSUE TITLE
Running virtualenv with interpreter /usr/local/opt/python@3.8/bin/python3

### ISSUE THREAD

**Issue by lingyunrh** [jeffreywildman/homebrew-virt-manager#149]
==> Installing virt-manager from jeffreywildman/virt-manager
==> Downloading https://virt-manager.org/download/sources/virt-manager/virt-manager-2.2.1.tar.gz
Already downloaded: /Users/songhongcheng/Library/Caches/Homebrew/downloads/77e22463a35b2e2bde8d02253c10129aabb1e5dfbfe2e6f33ef87bd35955dcf2--virt-manager-2.2.1.tar.gz
==> Patching
patching file virt-manager
Hunk #1 succeeded at 170 (offset 19 lines).
==> Downloading https://files.pythonhosted.org/packages/11/74/2c151a13ef41ab9fb43b3c4ff9e788e0496ed7923b2078d42cab30622bdf/vir
Already downloaded: /Users/songhongcheng/Library/Caches/Homebrew/downloads/507d2087bf24df82641b681a5fe4da778ef50ebe819a86ea1b584f70788f0f63--virtualenv-16.7.4.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/virt-manager--homebrew-virtualenv-20200408-859
==> python3 -s /private/tmp/virt-manager--homebrew-virtualenv-20200408-85974-61cctb/target/bin/virtualenv -p python3 /usr/loca
Last 15 lines from /Users/songhongcheng/Library/Logs/Homebrew/virt-manager/02.python3:
Traceback (most recent call last):
  File "/private/tmp/virt-manager--homebrew-virtualenv-20200408-85974-61cctb/target/lib/python3.8/site-packages/virtualenv.py", line 2632, in <module>
    main()
  File "/private/tmp/virt-manager--homebrew-virtualenv-20200408-85974-61cctb/target/lib/python3.8/site-packages/virtualenv.py", line 860, in main
    create_environment(
  File "/private/tmp/virt-manager--homebrew-virtualenv-20200408-85974-61cctb/target/lib/python3.8/site-packages/virtualenv.py", line 1173, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/private/tmp/virt-manager--homebrew-virtualenv-20200408-85974-61cctb/target/lib/python3.8/site-packages/virtualenv.py", line 1019, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/private/tmp/virt-manager--homebrew-virtualenv-20200408-85974-61cctb/target/lib/python3.8/site-packages/virtualenv.py", line 1110, in _install_wheel_with_search_dir
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=script)
  File "/private/tmp/virt-manager--homebrew-virtualenv-20200408-85974-61cctb/target/lib/python3.8/site-packages/virtualenv.py", line 963, in call_subprocess
    raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode))
OSError: Command /usr/local/Cellar/vi...ibexec/bin/python3.8 - setuptools pip wheel failed with error code 1
Running virtualenv with interpreter /usr/local/opt/python@3.8/bin/python3

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
Error installing virt-manager https://github.com/jeffreywildman/homebrew-virt-manager/issues/145
osx virt-manager console screen is black https://github.com/jeffreywildman/homebrew-virt-manager/issues/113
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62

**Comment by ssymes** [comment]
I observe this same error, as well, on my Mac.
I attempted an install of virt-manager on a new Mac running Catalina.
I have Python 3.8.5 installed in  **/usr/local/Cellar/python@3.8**



```
[ssymes@ss-mbp ~]$  python3 --version
Python 3.8.5

[ssymes@ss-mbp ~]$    brew install virt-manager virt-viewer

...LOTS OF OUTPUT INSTALLING DEPENDENCIES...

==> Installing jeffreywildman/virt-manager/virt-manager dependency: vte3
==> Pouring vte3-0.60.3_1.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/vte3/0.60.3_1: 123 files, 1.2MB
==> Installing jeffreywildman/virt-manager/virt-manager
==> Patching
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/virt-manager--homebrew-virtualenv-20200908-18988-13aqe1f/target --install-scripts=/private/tmp/v
==> python3 -s /private/tmp/virt-manager--homebrew-virtualenv-20200908-18988-13aqe1f/target/bin/virtualenv -p python3 /usr/local/Cellar/virt-manager/2.2.1_3/libexec
Last 15 lines from /Users/ssymes/Library/Logs/Homebrew/virt-manager/02.python3:
New python executable in /usr/local/Cellar/virt-manager/2.2.1_3/libexec/bin/python3.8
Also creating executable in /usr/local/Cellar/virt-manager/2.2.1_3/libexec/bin/python
Traceback (most recent call last):
  File "/private/tmp/virt-manager--homebrew-virtualenv-20200908-18988-13aqe1f/target/lib/python3.8/site-packages/virtualenv.py", line 2632, in <module>
    main()
  File "/private/tmp/virt-manager--homebrew-virtualenv-20200908-18988-13aqe1f/target/lib/python3.8/site-packages/virtualenv.py", line 860, in main
    create_environment(
  File "/private/tmp/virt-manager--homebrew-virtualenv-20200908-18988-13aqe1f/target/lib/python3.8/site-packages/virtualenv.py", line 1159, in create_environment
    install_distutils(home_dir)
  File "/private/tmp/virt-manager--homebrew-virtualenv-20200908-18988-13aqe1f/target/lib/python3.8/site-packages/virtualenv.py", line 1784, in install_distutils
    distutils_path = change_prefix(distutils.__path__[0], home_dir)
  File "/private/tmp/virt-manager--homebrew-virtualenv-20200908-18988-13aqe1f/target/lib/python3.8/site-packages/virtualenv.py", line 1267, in change_prefix
    assert False, "Filename {} does not start with any of these prefixes: {}".format(filename, prefixes)
AssertionError: Filename /usr/local/lib/python3.8/site-packages/setuptools/_distutils does not start with any of these prefixes: ['/private/tmp/virt-manager-20200908-18988-ptxyz9/virt-manager-2.2.1/.brew_home/Library/Python/3.8/lib/python/site-packages', '/private/tmp/virt-manager-20200908-18988-ptxyz9/virt-manager-2.2.1/.brew_home/.local/lib/python/3.8/site-packages', '/private/tmp/virt-manager-20200908-18988-ptxyz9/virt-manager-2.2.1/.brew_home/Library/Python/3.8/site-packages', '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/Extras/lib/python', '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8', '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8', '/Library/Python/3.8/site-packages']
Running virtualenv with interpreter /usr/local/opt/python@3.8/bin/python3

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
Error installing virt-manager https://github.com/jeffreywildman/homebrew-virt-manager/issues/145
osx virt-manager console screen is black https://github.com/jeffreywildman/homebrew-virt-manager/issues/113
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62
```
