### ISSUE TITLE
Error launching details: g-io-error-quark: Error opening file /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/pci.ids: No such file or directory (1)

### ISSUE THREAD

**Issue by binaryanomaly** [jeffreywildman/homebrew-virt-manager#151]
I can launch Virtual Machine Manager succesfully and connect to the KVM host via ssh. But when I want to open or create a new vm I get the error message below. Any ideas how this can be fixed?

`Error launching details: g-io-error-quark: Error opening file /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/pci.ids: No such file or directory (1)

Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtManager/vmwindow.py", line 39, in get_instance
    cls._instances[key] = vmmVMWindow(vm)
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtManager/vmwindow.py", line 76, in __init__
    self._details = vmmDetails(self.vm, self.builder, self.topwin,
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtManager/details/details.py", line 447, in __init__
    self.init_details()
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtManager/details/details.py", line 774, in init_details
    self._os_list = vmmOSList()
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtManager/oslist.py", line 39, in __init__
    self._init_state()
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtManager/oslist.py", line 55, in _init_state
    all_os = virtinst.OSDB.list_os()
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtinst/osdict.py", line 274, in list_os
    for name, osobj in self._all_variants.items():
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtinst/osdict.py", line 198, in _all_variants
    loader = self._os_loader
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtinst/osdict.py", line 190, in _os_loader
    loader.process_default_path()
gi.repository.GLib.GError: g-io-error-quark: Error opening file /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo/pci.ids: No such file or directory (1)`

**Comment by mcowart123** [comment]
Same thing here. A brew update yesterday seems to have hosed many things.

**Comment by LukasRypl** [comment]
Same here. To reduce interference, I have removed all versions and dependencies via `brew uninstall --force libvirt-glib gtk-vnc spice-gtk libvirt pygobject3 virt-manager virt-viewer` and then installed again. It did not help.

Version info:
```
brew info virt-manager                                                                                                                            26.05 2020 10:19:16 CEST

jeffreywildman/virt-manager/virt-manager: stable 2.2.1
App for managing virtual machines
https://virt-manager.org/
/usr/local/Cellar/virt-manager/2.2.1_3 (1,739 files, 22.5MB) *
  Built from source on 2020-05-26 at 10:06:30
From: https://github.com/jeffreywildman/homebrew-virt-manager/blob/master/virt-manager.rb
==> Dependencies
Build: intltool ✔, pkg-config ✔
Required: adwaita-icon-theme ✔, gtk+3 ✔, gtk-vnc ✔, gtksourceview4 ✔, hicolor-icon-theme ✔, libosinfo ✔, libvirt ✔, libvirt-glib ✔, libxml2 ✔, osinfo-db ✔, py3cairo ✔, pygobject3 ✔, python ✔, spice-gtk ✔, vte3 ✔
```

**Comment by LukasRypl** [comment]
`pci.ids` file comes from https://gitlab.com/libosinfo/libosinfo/-/blob/master/build-aux/download_pci_ids
the other missing file is `usb.ids` from the same source.

Ugly fix:
```
mkdir /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo
cd /usr/local/Cellar/libosinfo/1.7.1/share/libosinfo
wget -q -O pci.ids http://pciids.sourceforge.net/v2.2/pci.ids
wget -q -O usb.ids http://www.linux-usb.org/usb.ids
```

**Comment by mcowart123** [comment]
I had some other issues and did a complete uninstall/reinstall of homebrew. Issue persists with virt-manager.

**Comment by binaryanomaly** [comment]
I installed this on vanilla homebrew so the cause is likely not an existing installation of brew.

**Comment by mcowart123** [comment]
Has there been any update on this? I know virt-manager is technically deprecated but there's nothing else out there GUI-wise that has as much functionality.

**Comment by thna123459** [comment]
Same issue here. The manual workaround for libosinfo 1.8.0 was effective.

**Comment by jouve** [comment]
https://github.com/Homebrew/homebrew-core/pull/58285

**Comment by jouve** [comment]
fixed in homebrew-core (1.8.0_1)
