### ISSUE TITLE
ModuleNotFoundError: No module named 'gi'

### ISSUE THREAD

**Issue by TorinKR** [jeffreywildman/homebrew-virt-manager#156]
Hi! After upgrading to Big Sur, I ran brew update, then brew upgrade, and the vast majority of programs work. But virt-manager doesn't start with the message:
ModuleNotFoundError: No module named 'gi'
How to fix it????

Torin

**Comment by zdzichu6969** [comment]
1. Uninstall virt-manager `brew uninstall virt-manager virt-viewer`
2. Uninstall deps `brew bundle dump
brew bundle --force cleanup `
3. Update xcode `xcode-select --install`
4. Install `brew install virt-manager virt-viewer`

Work for me.

**Comment by TorinKR** [comment]
Helou Mateusz :)
It was a good lead! It turned out that my CLT did not update correctly. Manually crashing and reinstalling clt allowed to run virt-manager.
Success!
But not completely :/
I cannot start the machine preview.
```
Clicking open crashes such errors:
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtManager/vmwindow.py", line 39, in get_instance
    cls._instances [key] = vmmVMWindow (vm)
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtManager/vmwindow.py", line 76, in __init__
    self._details = vmmDetails (self.vm, self.builder, self.topwin,
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtManager/details/details.py", line 447, in __init__
    self.init_details ()
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtManager/details/details.py", line 879, in init_details
    vmmAddHardware.build_network_model_combo (self.vm, net_model)
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtManager/addhardware.py", line 792, in build_network_model_combo
    vmmAddHardware.populate_network_model_combo (vm, combo)
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtManager/addhardware.py", line 787, in populate_network_model_combo
    combo, DeviceInterface.default_model (vm.xmlobj))
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtinst/devices/interface.py", line 261, in default_model
    supported_models = guest.osinfo.supported_netmodels ()
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtinst/osdict.py", line 478, in supported_netmodels
    return self._device_filter (cls = "net")
  File "/usr/local/Cellar/virt-manager/2.2.1_3/libexec/share/virt-manager/virtinst/osdict.py", line 415, in _device_filter
    if cls and not re.match (cls, dev.get_class ()):
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/re.py", line 191, in match
    return _compile (pattern, flags) .match (string)
TypeError: expected string or bytes-like object
```

And a lot :)

<polish mode on>
witam Włocławianina - kurde przez tą pan.dem.ie to dawno w moim ulubionym (zaraz po Krk of kors) mieście nie byłem :) 
</polish mode off>

**Comment by nielsk** [comment]
I tried re-installing as suggested above and now I get:

```
==> Installing jeffreywildman/virt-manager/virt-manager
==> Patching
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/virt-manager--homebrew-virtualenv-20201204-88402-6rsv
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/virt-manager--homebrew-virtualenv-20201204-88402-6rsv
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/virt-manager--homebrew-virtualenv-20201204-88402-6rsv
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/virt-manager--homebrew-virtualenv-20201204-88402-6rsv
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/virt-manager--homebrew-virtualenv-20201204-88402-6rsv
==> python3 -s /private/tmp/virt-manager--homebrew-virtualenv-20201204-88402-6rsv69/target/bin/virtualenv -p python3 /usr/local/Cella
==> /usr/local/Cellar/virt-manager/2.2.1_3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/vir
Last 15 lines from /Users/nik/Library/Logs/Homebrew/virt-manager/07.pip:
  Found link https://files.pythonhosted.org/packages/73/8e/7774190ac616c69194688ffce7c1b2a097749792fea42e390e7ddfdef8bc/pip-20.2.2.tar.gz#sha256=58a3b0b55ee2278104165c7ee7bc8e2db6f635067f3c66cf637113ec5aa71584 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.2.2
  Found link https://files.pythonhosted.org/packages/4e/5f/528232275f6509b1fff703c9280e58951a81abe24640905de621c9f81839/pip-20.2.3-py2.py3-none-any.whl#sha256=0f35d63b7245205f4060efe1982f5ea2196aa6e5b26c07669adcf800e2542026 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.2.3
  Found link https://files.pythonhosted.org/packages/59/64/4718738ffbc22d98b5223dbd6c5bb87c476d83a4c71719402935170064c7/pip-20.2.3.tar.gz#sha256=30c70b6179711a7c4cf76da89e8a0f5282279dfb0278bec7b94134be92543b6d (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.2.3
  Found link https://files.pythonhosted.org/packages/cb/28/91f26bd088ce8e22169032100d4260614fc3da435025ff389ef1d396a433/pip-20.2.4-py2.py3-none-any.whl#sha256=51f1c7514530bd5c145d8f13ed936ad6b8bfcb8cf74e10403d0890bc986f0033 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.2.4
  Found link https://files.pythonhosted.org/packages/0b/f5/be8e741434a4bf4ce5dbc235aa28ed0666178ea8986ddc10d035023744e6/pip-20.2.4.tar.gz#sha256=85c99a857ea0fb0aedf23833d9be5c40cf253fe24443f0829c7b472e23c364a1 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.2.4
  Found link https://files.pythonhosted.org/packages/fb/46/26d13ba147ba430f9cda0d0cf599a041d142a5c8b1a90ff845ebce7fba0f/pip-20.3b1-py2.py3-none-any.whl#sha256=122fcd82deac1153c1699f29815bfab3f876e5bbe018cc2df1297f9802572a97 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3b1
  Found link https://files.pythonhosted.org/packages/7f/61/2da3c027ad7bd4bc87a3ee7e7160c93e7500dac3536e02ff93008e9b3460/pip-20.3b1.tar.gz#sha256=819c710a5c8d8c5e44695d03e51cb23b08c070e1ae6a5d6910a89e248e0ff29c (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3b1
  Found link https://files.pythonhosted.org/packages/55/73/bce122d1ed0217b3c1a3439ab16dfa94bbeabd0d31755fcf907493abf39b/pip-20.3-py2.py3-none-any.whl#sha256=3236fe7288d155c238bb6c85d3e784db3a8e592e827b83fea4d36d8b749ecc4b (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3
  Found link https://files.pythonhosted.org/packages/03/41/6da553f689d530bc2c337d2c496a40dc9c0fdc6481e5df1f3ee3b8574479/pip-20.3.tar.gz#sha256=9ae7ca6656eac22d2a9b49d024fc24e00f68f4c4d4db673d2d9b525c3dea6e0e (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3
  Found link https://files.pythonhosted.org/packages/ab/11/2dc62c5263d9eb322f2f028f7b56cd9d096bb8988fcf82d65fa2e4057afe/pip-20.3.1-py2.py3-none-any.whl#sha256=425e79b20939abbffa7633a91151a882aedc77564d9313e3584eb0416c28c558 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3.1
  Found link https://files.pythonhosted.org/packages/cb/5f/ae1eb8bda1cde4952bd12e468ab8a254c345a0189402bf1421457577f4f3/pip-20.3.1.tar.gz#sha256=43f7d3811f05db95809d39515a5111dd05994965d870178a4fe10d5482f9d2e2 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3.1
Given no hashes to check 153 links for project 'pip': discarding no candidates
WARNING: You are using pip version 20.2.4; however, version 20.3.1 is available.
You should consider upgrading via the '/usr/local/Cellar/virt-manager/2.2.1_3/libexec/bin/python -m pip install --upgrade pip' command.
Removed build tracker: '/private/tmp/pip-req-tracker-tzs5d6ll'
```

MacOS 10.15
