### ISSUE TITLE
virt-manager on m1

### ISSUE THREAD

**Issue by depeo** [jeffreywildman/homebrew-virt-manager#167]
Hi,

Has anyone been able to get virt-manager to work on M1 Macs?

On brew m1 It actually installs after changing libvirt-python version to 7.10, but I get this error when starting it:

```

** (process:13966): WARNING **: 16:42:49.971: Failed to load shared library 'libpango-1.0.0.dylib' referenced by the typelib: dlopen(libpango-1.0.0.dylib, 9): image not found
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/virt-manager/3.2.0/libexec/bin/virt-manager", line 8, in <module>
    virtmanager.runcli()
  File "/opt/homebrew/Cellar/virt-manager/3.2.0/libexec/share/virt-manager/virtManager/virtmanager.py", line 267, in runcli
    main()
  File "/opt/homebrew/Cellar/virt-manager/3.2.0/libexec/share/virt-manager/virtManager/virtmanager.py", line 191, in main
    leftovers = _import_gtk(leftovers)
  File "/opt/homebrew/Cellar/virt-manager/3.2.0/libexec/share/virt-manager/virtManager/virtmanager.py", line 58, in _import_gtk
    from gi.repository import Gtk
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/Cellar/virt-manager/3.2.0/libexec/lib/python3.9/site-packages/gi/importer.py", line 144, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/Cellar/virt-manager/3.2.0/libexec/lib/python3.9/site-packages/gi/importer.py", line 144, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/Cellar/virt-manager/3.2.0/libexec/lib/python3.9/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/opt/homebrew/Cellar/virt-manager/3.2.0/libexec/lib/python3.9/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/homebrew/Cellar/virt-manager/3.2.0/libexec/lib/python3.9/site-packages/gi/overrides/Pango.py", line 41, in <module>
    FontDescription = override(FontDescription)
  File "/opt/homebrew/Cellar/virt-manager/3.2.0/libexec/lib/python3.9/site-packages/gi/overrides/__init__.py", line 195, in override
    assert g_type != TYPE_NONE
AssertionError
```
The file it complains about exists here:
```
/opt/homebrew/Cellar/pango/HEAD-9be0d6e/lib/libpango-1.0.0.dylib`
```
I also tried to install the intel version of Brew, but when trying to install virt-manager, I get this error:

```==> Downloading https://download.gnome.org/sources/gobject-introspection/1.66/gobject-introspection-1.66.1.tar.xz
Already downloaded: /Users/dp/Library/Caches/Homebrew/downloads/40c372030be750220c27908ef4d744abf2262f31d6a4bea14f3e8fa4857e15ee--gobject-introspection-1.66.1.tar.xz
==> meson --prefix=/opt/local/Homebrew/Cellar/gobject-introspection/1.66.1_1 --libdir=/opt/local/Homebrew/Cellar/gobject-introspection/1.66.1_1/lib --buildtype=release --wrap-mode=n
==> ninja -v
Last 15 lines from /Users/dp/Library/Logs/Homebrew/gobject-introspection/02.ninja:
../tests/gimarshallingtests.c:5331: Warning: GIMarshallingTests: gi_marshalling_tests_gerror_out_transfer_none: argument err: Unresolved type: 'GError**'
../tests/gimarshallingtests.c:5356: Warning: GIMarshallingTests: gi_marshalling_tests_gerror_return: return value: Unresolved type: 'GError*'
../tests/gimarshallingtests.c:5481: Warning: GIMarshallingTests: gi_marshalling_tests_param_spec_in_bool: argument param: Unresolved type: 'GParamSpec*'
../tests/gimarshallingtests.c:5495: Warning: GIMarshallingTests: gi_marshalling_tests_param_spec_return: return value: Unresolved type: 'GParamSpec*'
../tests/gimarshallingtests.c:5503: Warning: GIMarshallingTests: gi_marshalling_tests_param_spec_out: argument param: Unresolved type: 'GParamSpec**'
../tests/gimarshallingtests.h:1594: Warning: GIMarshallingTests: gi_marshalling_tests_object_method_variant_array_in: argument in: Unresolved type: 'GVariant**'
../tests/gimarshallingtests.c:4654: Warning: GIMarshallingTests: gi_marshalling_tests_object_vfunc_caller_allocated_out_parameter: argument a: Unresolved type: 'GValue*'
<unknown>:: Fatal: GIMarshallingTests: warnings configured as fatal
<unknown>:: Fatal: GIMarshallingTests: warnings configured as fatal

[149/163] /opt/local/Homebrew/opt/python@3.9/bin/python3 tools/g-ir-scanner --quiet --output=tests/Everything-1.0.gir --no-libtool --reparse-validate --add-include-path /private/tmp/gobject-introspection-20210304-10283-lvnp49/gobject-introspection-1.66.1/gir --add-include-path /private/tmp/gobject-introspection-20210304-10283-lvnp49/gobject-introspection-1.66.1/build/gir --warn-all --warn-error --namespace=Everything --nsversion=1.0 --include=Gio-2.0 --library=everything-1.0 -L /private/tmp/gobject-introspection-20210304-10283-lvnp49/gobject-introspection-1.66.1/build/tests -I /private/tmp/gobject-introspection-20210304-10283-lvnp49/gobject-introspection-1.66.1/tests tests/everything.c tests/everything.h
[150/163] /opt/local/Homebrew/opt/python@3.9/bin/python3 tools/g-ir-scanner --quiet --output=tests/scanner/Headeronly-1.0.gir --no-libtool --warn-all --warn-error --reparse-validate --namespace=Headeronly --nsversion=1.0 --header-only ../tests/scanner/headeronly.h
[151/163] /opt/local/Homebrew/opt/python@3.9/bin/python3 tools/g-ir-scanner --quiet --output=tests/scanner/Identfilter-1.0.gir --no-libtool --accept-unprefixed --reparse-validate --namespace=Identfilter --nsversion=1.0 --header-only '--identifier-filter-cmd=/opt/local/homebrew/Cellar/python@3.9/3.9.2_1/bin/python3 /private/tmp/gobject-introspection-20210304-10283-lvnp49/gobject-introspection-1.66.1/tests/scanner/identfilter.py' ../tests/scanner/identfilter.h
[152/163] /opt/local/Homebrew/opt/python@3.9/bin/python3 tools/g-ir-scanner --quiet --output=tests/scanner/Symbolfilter-1.0.gir --no-libtool --reparse-validate --namespace=Symbolfilter --nsversion=1.0 --header-only '--symbol-filter-cmd=/opt/local/homebrew/Cellar/python@3.9/3.9.2_1/bin/python3 /private/tmp/gobject-introspection-20210304-10283-lvnp49/gobject-introspection-1.66.1/tests/scanner/symbolfilter.py' ../tests/scanner/symbolfilter.h
ninja: build stopped: subcommand failed.
```

**Comment by depeo** [comment]
I'll just use X Forwarding instead
