### ISSUE TITLE
Assertion Error When Running Virt-Manager on MacOS BigSur

### ISSUE THREAD

**Issue by TheKapn** [jeffreywildman/homebrew-virt-manager#174]
When trying  to run virt-manager on MacOS, 11.3, I get the following error:

Any suggestions on how I can resolve this?

Thanks in advance.
T-C

[Tue, 04 May 2021 14:46:30 virt-manager 1731] DEBUG (cli:204) Launched with command line: /opt/homebrew/Cellar/virt-manager/3.2.0_3/libexec/bin/virt-manager --debug --no-fork
[Tue, 04 May 2021 14:46:30 virt-manager 1731] DEBUG (virtmanager:163) virt-manager version: 3.2.0
[Tue, 04 May 2021 14:46:30 virt-manager 1731] DEBUG (virtmanager:164) virtManager import: /opt/homebrew/Cellar/virt-manager/3.2.0_3/libexec/share/virt-manager/virtManager

** (process:1731): WARNING **: 14:46:30.495: Failed to load shared library 'libpango-1.0.0.dylib' referenced by the typelib: dlopen(libpango-1.0.0.dylib, 9): image not found
[Tue, 04 May 2021 14:46:30 virt-manager 1731] DEBUG (cli:195) Uncaught exception:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/virt-manager/3.2.0_3/libexec/bin/virt-manager", line 8, in <module>
    virtmanager.runcli()
  File "/opt/homebrew/Cellar/virt-manager/3.2.0_3/libexec/share/virt-manager/virtManager/virtmanager.py", line 267, in runcli
    main()
  File "/opt/homebrew/Cellar/virt-manager/3.2.0_3/libexec/share/virt-manager/virtManager/virtmanager.py", line 191, in main
    leftovers = _import_gtk(leftovers)
  File "/opt/homebrew/Cellar/virt-manager/3.2.0_3/libexec/share/virt-manager/virtManager/virtmanager.py", line 58, in _import_gtk
    from gi.repository import Gtk
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/opt/pygobject3/lib/python3.9/site-packages/gi/importer.py", line 144, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/opt/pygobject3/lib/python3.9/site-packages/gi/importer.py", line 144, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/opt/pygobject3/lib/python3.9/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/opt/homebrew/opt/pygobject3/lib/python3.9/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/homebrew/opt/pygobject3/lib/python3.9/site-packages/gi/overrides/Pango.py", line 41, in <module>
    FontDescription = override(FontDescription)
  File "/opt/homebrew/opt/pygobject3/lib/python3.9/site-packages/gi/overrides/__init__.py", line 195, in override
    assert g_type != TYPE_NONE
AssertionError

**Comment by shah-nimisha** [comment]
Same issue. MacOS BigSur, 11.3.1

**Comment by mars1512** [comment]
Same issue. MacOS BigSur, 11.3.1
