### ISSUE TITLE
Big Sur - Issues installing

### ISSUE THREAD

**Issue by waltervalderrama** [jeffreywildman/homebrew-virt-manager#175]
Besides trying to install virt-manager several times, I still can't get it working. This is the exit from CLI:

==> Installing jeffreywildman/virt-manager/virt-manager
==> Patching
==> python3 -m venv /usr/local/Cellar/virt-manager/2.2.1_3/libexec
==> /usr/local/Cellar/virt-manager/2.2.1_3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/virt-manager-
Last 15 lines from /Users/waltervalderrama/Library/Logs/Homebrew/virt-manager/02.pip:
  Found link https://files.pythonhosted.org/packages/54/eb/4a3642e971f404d69d4f6fa3885559d67562801b99d7592487f1ecc4e017/pip-20.3.3-py2.py3-none-any.whl#sha256=fab098c8a1758295dd9f57413c199f23571e8fde6cc39c22c78c961b4ac6286d (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3.3
  Found link https://files.pythonhosted.org/packages/ca/1e/d91d7aae44d00cd5001957a1473e4e4b7d1d0f072d1af7c34b5899c9ccdf/pip-20.3.3.tar.gz#sha256=79c1ac8a9dccbec8752761cb5a2df833224263ca661477a2a9ed03ddf4e0e3ba (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3.3
  Found link https://files.pythonhosted.org/packages/27/79/8a850fe3496446ff0d584327ae44e7500daf6764ca1a382d2d02789accf7/pip-20.3.4-py2.py3-none-any.whl#sha256=217ae5161a0e08c0fb873858806e3478c9775caffce5168b50ec885e358c199d (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3.4
  Found link https://files.pythonhosted.org/packages/53/7f/55721ad0501a9076dbc354cc8c63ffc2d6f1ef360f49ad0fbcce19d68538/pip-20.3.4.tar.gz#sha256=6773934e5f5fc3eaa8c5a44949b5b924fc122daa0a8aa9f80c835b4ca2a543fc (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3.4
  Found link https://files.pythonhosted.org/packages/de/47/58b9f3e6f611dfd17fb8bd9ed3e6f93b7ee662fb85bdfee3565e8979ddf7/pip-21.0-py3-none-any.whl#sha256=cf2410eedf8735fd842e0fecd4117ca79025d7fe7c161e32f8640ed6ebe5ecb9 (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.0
  Found link https://files.pythonhosted.org/packages/9e/24/bc928987f35dd0167f21b13a1777c21b9c5917c9894cff93f1c1a6cb8f3b/pip-21.0.tar.gz#sha256=b330cf6467afd5d15f4c1c56f5c95e56a2bfb941c869bed4c1aa517bcb16de25 (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.0
  Found link https://files.pythonhosted.org/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl#sha256=37fd50e056e2aed635dec96594606f0286640489b0db0ce7607f7e51890372d5 (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.0.1
  Found link https://files.pythonhosted.org/packages/b7/2d/ad02de84a4c9fd3b1958dc9fb72764de1aa2605a9d7e943837be6ad82337/pip-21.0.1.tar.gz#sha256=99bbde183ec5ec037318e774b0d8ae0a64352fe53b2c7fd630be1d07e94f41e5 (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.0.1
  Found link https://files.pythonhosted.org/packages/ac/cf/0cc542fc93de2f3b9b53cb979c7d1118cffb93204afb46299a9f858e113f/pip-21.1-py3-none-any.whl#sha256=ea9f2668484893e90149fd5a6124e04651ffedd67203a8aaf030d31406b937a4 (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.1
  Found link https://files.pythonhosted.org/packages/de/62/77b8b1a9f9c710988e5a58c22a7cd025b63b204df57a6ea939d6d39da421/pip-21.1.tar.gz#sha256=a810bf07c3723a28621c29abe8e34429fa082c337f89aea9a795865416b66d3e (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.1
  Found link https://files.pythonhosted.org/packages/cd/6f/43037c7bcc8bd8ba7c9074256b1a11596daa15555808ec748048c1507f08/pip-21.1.1-py3-none-any.whl#sha256=11d095ed5c15265fc5c15cc40a45188675c239fb0f9913b673a33e54ff7d45f0 (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.1.1
  Found link https://files.pythonhosted.org/packages/94/b0/e10bdc8809c81796c80aa3644a8e3dc16594fb1bd68f5996929f26cad980/pip-21.1.1.tar.gz#sha256=51ad01ddcd8de923533b01a870e7b987c2eb4d83b50b89e1bf102723ff9fed8b (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.1.1
Skipping link: not a file: https://pypi.org/simple/pip/
Given no hashes to check 165 links for project 'pip': discarding no candidates
Removed build tracker: '/private/tmp/pip-req-tracker-2gvgob_f'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
virt-manager: command not found https://github.com/jeffreywildman/homebrew-virt-manager/issues/169
Assertion Error When Running Virt-Manager on MacOS BigSur https://github.com/jeffreywildman/homebrew-virt-manager/issues/174
virt-manager broken on Big Sur after minor update https://github.com/jeffreywildman/homebrew-virt-manager/issues/170
bump virt-manager/view-viewer and deps https://github.com/jeffreywildman/homebrew-virt-manager/pull/166
cannot install virt-manager, error with python version despite having python 3.9 installed https://github.com/jeffreywildman/homebrew-virt-manager/issues/172
Virt-manager wont build. Update to libvirt-python https://github.com/jeffreywildman/homebrew-virt-manager/pull/171
Error installing virt-manager https://github.com/jeffreywildman/homebrew-virt-manager/issues/145
osx virt-manager console screen is black https://github.com/jeffreywildman/homebrew-virt-manager/issues/113
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62

**Comment by r3dhat22** [comment]
I have exactly the same problem

brew install jeffreywildman/virt-manager/virt-manager
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 8 formulae.

==> Installing virt-manager from jeffreywildman/virt-manager
==> Downloading https://libvirt.org/sources/python/libvirt-python-6.10.0.tar.gz
Already downloaded: /Users/redhat/Library/Caches/Homebrew/downloads/c0ea3dcb750aed089cfed8d3988e3aef79b70d635cfd42c87db147e860647de4--libvirt-python-6.10.0.tar.gz
==> Downloading https://pypi.io/packages/source/i/idna/idna-2.8.tar.gz
Already downloaded: /Users/redhat/Library/Caches/Homebrew/downloads/89cd3c9503f30cf4794067fbb3bb85881a04d4a79002cd52dd006617f4dee6d5--idna-2.8.tar.gz
==> Downloading https://pypi.io/packages/source/c/certifi/certifi-2019.11.28.tar.gz
Already downloaded: /Users/redhat/Library/Caches/Homebrew/downloads/d305888203f80870f04cbff5b615679be127a718ffeec3b3ce5db16bdc4abfa2--certifi-2019.11.28.tar.gz
==> Downloading https://pypi.io/packages/source/c/chardet/chardet-3.0.4.tar.gz
Already downloaded: /Users/redhat/Library/Caches/Homebrew/downloads/0b520e43abac95fdb4182899f49c1c7ced69c67c4bc132b3801691b993eb33f9--chardet-3.0.4.tar.gz
==> Downloading https://pypi.io/packages/source/u/urllib3/urllib3-1.25.7.tar.gz
Already downloaded: /Users/redhat/Library/Caches/Homebrew/downloads/04dc027e49125d42a130fd408cde60c9d9a87ce021683a3e49bf067a62316261--urllib3-1.25.7.tar.gz
==> Downloading https://pypi.io/packages/source/r/requests/requests-2.22.0.tar.gz
Already downloaded: /Users/redhat/Library/Caches/Homebrew/downloads/4253f7dff3c4f4a5a7fe142af689d95ed2e77979f696451a78d96412e90b0f94--requests-2.22.0.tar.gz
==> Downloading https://virt-manager.org/download/sources/virt-manager/virt-manager-2.2.1.tar.gz
Already downloaded: /Users/redhat/Library/Caches/Homebrew/downloads/77e22463a35b2e2bde8d02253c10129aabb1e5dfbfe2e6f33ef87bd35955dcf2--virt-manager-2.2.1.tar.gz
==> Patching
==> python3 -m venv /usr/local/Cellar/virt-manager/2.2.1_3/libexec
==> /usr/local/Cellar/virt-manager/2.2.1_3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/virt-manager--libvirt-python-20210519-25607-705nwm/libvirt-p
Last 15 lines from /Users/redhat/Library/Logs/Homebrew/virt-manager/02.pip:
  Found link https://files.pythonhosted.org/packages/54/eb/4a3642e971f404d69d4f6fa3885559d67562801b99d7592487f1ecc4e017/pip-20.3.3-py2.py3-none-any.whl#sha256=fab098c8a1758295dd9f57413c199f23571e8fde6cc39c22c78c961b4ac6286d (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3.3
  Found link https://files.pythonhosted.org/packages/ca/1e/d91d7aae44d00cd5001957a1473e4e4b7d1d0f072d1af7c34b5899c9ccdf/pip-20.3.3.tar.gz#sha256=79c1ac8a9dccbec8752761cb5a2df833224263ca661477a2a9ed03ddf4e0e3ba (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3.3
  Found link https://files.pythonhosted.org/packages/27/79/8a850fe3496446ff0d584327ae44e7500daf6764ca1a382d2d02789accf7/pip-20.3.4-py2.py3-none-any.whl#sha256=217ae5161a0e08c0fb873858806e3478c9775caffce5168b50ec885e358c199d (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3.4
  Found link https://files.pythonhosted.org/packages/53/7f/55721ad0501a9076dbc354cc8c63ffc2d6f1ef360f49ad0fbcce19d68538/pip-20.3.4.tar.gz#sha256=6773934e5f5fc3eaa8c5a44949b5b924fc122daa0a8aa9f80c835b4ca2a543fc (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3.4
  Found link https://files.pythonhosted.org/packages/de/47/58b9f3e6f611dfd17fb8bd9ed3e6f93b7ee662fb85bdfee3565e8979ddf7/pip-21.0-py3-none-any.whl#sha256=cf2410eedf8735fd842e0fecd4117ca79025d7fe7c161e32f8640ed6ebe5ecb9 (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.0
  Found link https://files.pythonhosted.org/packages/9e/24/bc928987f35dd0167f21b13a1777c21b9c5917c9894cff93f1c1a6cb8f3b/pip-21.0.tar.gz#sha256=b330cf6467afd5d15f4c1c56f5c95e56a2bfb941c869bed4c1aa517bcb16de25 (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.0
  Found link https://files.pythonhosted.org/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl#sha256=37fd50e056e2aed635dec96594606f0286640489b0db0ce7607f7e51890372d5 (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.0.1
  Found link https://files.pythonhosted.org/packages/b7/2d/ad02de84a4c9fd3b1958dc9fb72764de1aa2605a9d7e943837be6ad82337/pip-21.0.1.tar.gz#sha256=99bbde183ec5ec037318e774b0d8ae0a64352fe53b2c7fd630be1d07e94f41e5 (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.0.1
  Found link https://files.pythonhosted.org/packages/ac/cf/0cc542fc93de2f3b9b53cb979c7d1118cffb93204afb46299a9f858e113f/pip-21.1-py3-none-any.whl#sha256=ea9f2668484893e90149fd5a6124e04651ffedd67203a8aaf030d31406b937a4 (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.1
  Found link https://files.pythonhosted.org/packages/de/62/77b8b1a9f9c710988e5a58c22a7cd025b63b204df57a6ea939d6d39da421/pip-21.1.tar.gz#sha256=a810bf07c3723a28621c29abe8e34429fa082c337f89aea9a795865416b66d3e (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.1
  Found link https://files.pythonhosted.org/packages/cd/6f/43037c7bcc8bd8ba7c9074256b1a11596daa15555808ec748048c1507f08/pip-21.1.1-py3-none-any.whl#sha256=11d095ed5c15265fc5c15cc40a45188675c239fb0f9913b673a33e54ff7d45f0 (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.1.1
  Found link https://files.pythonhosted.org/packages/94/b0/e10bdc8809c81796c80aa3644a8e3dc16594fb1bd68f5996929f26cad980/pip-21.1.1.tar.gz#sha256=51ad01ddcd8de923533b01a870e7b987c2eb4d83b50b89e1bf102723ff9fed8b (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.1.1
Skipping link: not a file: https://pypi.org/simple/pip/
Given no hashes to check 165 links for project 'pip': discarding no candidates
Removed build tracker: '/private/tmp/pip-req-tracker-nloo57ps'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
virt-manager: command not found https://github.com/jeffreywildman/homebrew-virt-manager/issues/169
Assertion Error When Running Virt-Manager on MacOS BigSur https://github.com/jeffreywildman/homebrew-virt-manager/issues/174
virt-manager broken on Big Sur after minor update https://github.com/jeffreywildman/homebrew-virt-manager/issues/170
bump virt-manager/view-viewer and deps https://github.com/jeffreywildman/homebrew-virt-manager/pull/166
cannot install virt-manager, error with python version despite having python 3.9 installed https://github.com/jeffreywildman/homebrew-virt-manager/issues/172
Virt-manager wont build. Update to libvirt-python https://github.com/jeffreywildman/homebrew-virt-manager/pull/171
Error installing virt-manager https://github.com/jeffreywildman/homebrew-virt-manager/issues/145
osx virt-manager console screen is black https://github.com/jeffreywildman/homebrew-virt-manager/issues/113
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62

**Comment by langesmalle** [comment]
Same here.
When can we expect a fix?

**Comment by BirknerAlex** [comment]
There is a workaround for this issue already: https://github.com/jeffreywildman/homebrew-virt-manager/issues/173#issuecomment-837749616

**Comment by langesmalle** [comment]
OK, tried this one and fails with:

==> Installing arthurk/virt-manager/virt-manager dependency: osinfo-db-tools
==> meson setup builddir --prefix=/usr/local/Cellar/osinfo-db-tools/1.9.0 --localstatedir=/usr/local/var --sysconfdir=
==> ninja -C builddir
==> ninja -C builddir install
Last 15 lines from /Users/XYZ/Library/Logs/Homebrew/osinfo-db-tools/03.ninja:
ninja: Entering directory `builddir'
[0/1] Installing files.
Traceback (most recent call last):
  File "/usr/local/Cellar/meson/0.58.0/libexec/bin/meson", line 33, in <module>
    sys.exit(load_entry_point('meson==0.58.0', 'console_scripts', 'meson')())
  File "/usr/local/Cellar/meson/0.58.0/libexec/bin/meson", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: meson
FAILED: meson-install
/usr/local/Cellar/meson/0.58.0/libexec/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
