### ISSUE TITLE
Libvirt service must be started 

### ISSUE THREAD

**Issue by tristan-k** [jeffreywildman/homebrew-virt-manager#19]
For some reason virt-manager cant connect to libvirtd.

```
Mit libvirt konnte nicht verbunden werden.

Stellen Sie sicher, dass der »libvirtd«-Dienst läuft.

Libvirt URI is: qemu:///system

Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/1.2.1/libexec/share/virt-manager/virtManager/connection.py", line 862, in _do_open
    self._backend.open(self._do_creds_password)
  File "/usr/local/Cellar/virt-manager/1.2.1/libexec/share/virt-manager/virtinst/connection.py", line 161, in open
    open_flags)
  File "/usr/local/Cellar/virt-manager/1.2.1/libexec/vendor/lib/python2.7/site-packages/libvirt.py", line 105, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirtError: Failed to connect socket to '/usr/local/var/run/libvirt/libvirt-sock': No such file or directory
```
![ishot-116](https://cloud.githubusercontent.com/assets/732025/8251706/1b8cee9c-167f-11e5-8216-a8c74915a0e3.jpg)

**Comment by jeffreywildman** [comment]
Hi, thanks for the message.  I have not previously tried connecting to a local qemu hypervisor.  Upon attempting the following, I can confirm getting the same error as you:

`$ virt-manager -c qemu:///system`

I've primarily used virt-manager to connect to remote hypervisors, but have been able to use virt-manager to connect to a local virtual box hypervisor:

`$ virt-manager -c vbox:///session`

**Comment by ankitsharda** [comment]
I'm facing the exact same problem when I try to connect to a remote hypervisor. Any ideas on what could be causing this ?

**Comment by jeffreywildman** [comment]
Hi @ankitsharda, is the remote URI correct?  I would try the URI with ```virsh``` to confirm.

**Comment by ankitsharda** [comment]
Yes the remote URI is correct. I am able to connect fine with the same URI from another host (running Kali Linux , a fork of Debian)

**Comment by jeffreywildman** [comment]
I would still recommend trying to use ```virsh``` from the same local machine that produced the ```virt-manager``` error to confirm that the URI works from the local machine.

**Comment by RocKordier** [comment]
Hey Folks,

i've got nearly the same issue and a possible solution today. I tried to connect to a new remote hypervisor. The connection failed with the following error:

>Mit libvirt konnte nicht verbunden werden.
>internal error: received hangup / error event on socket

>Stellen Sie sicher, dass der «libvirtd»-Daemon auf dem entfernten Host läuft.

> Libvirt URI is: qemu+ssh://[IP]/system?socket=/var/run/libvirt/libvirt-sock

>Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/1.2.0/libexec/share/virt-manager/virtManager/connection.py", line 861, in _do_open self._backend.open(self._do_creds_password)
 File "/usr/local/Cellar/virt-manager/1.2.0/libexec/share/virt-manager/virtinst/connection.py", line 161, in open open_flags)
  File "/usr/local/Cellar/virt-manager/1.2.0/libexec/vendor/lib/python2.7/site-packages/libvirt.py", line 105, in openAuth if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirtError: internal error: received hangup / error event on socket

After i've connected to the host via ssh and the fingerprint was added to the ~/.ssh/known_hosts - file everything works fine!

**Comment by jeffreywildman** [comment]
Closing due to inactivity, but thanks for the possible solution @RocKordier.

**Comment by Philelis** [comment]
Same error for local Server:
```
Unable to connect to libvirt.

Verify that the 'libvirtd' daemon is running.

Libvirt URI is: qemu:///system

Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/1.2.1/libexec/share/virt-manager/virtManager/connection.py", line 862, in _do_open
    self._backend.open(self._do_creds_password)
  File "/usr/local/Cellar/virt-manager/1.2.1/libexec/share/virt-manager/virtinst/connection.py", line 161, in open
    open_flags)
  File "/usr/local/Cellar/virt-manager/1.2.1/libexec/vendor/lib/python2.7/site-packages/libvirt.py", line 105, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirtError: Failed to connect socket to '/usr/local/var/run/libvirt/libvirt-sock': No such file or directory
```

**Comment by jeffreywildman** [comment]
@Philelis Do you have QEMU installed?  Unfortunately, I don't have experience running QEMU on OSX (if possible) nor connecting to the local QEMU hypervisor using virt-manager.  My suggestion would be to troubleshoot the correct URI using virsh before attempting it with virt-manager.

**Comment by Philelis** [comment]
@jeffreywildman No it was not, but now. Therefore I have one problem. I don't know how to use it :D (http://brewformulas.org/Qemu).

**Comment by wadaki** [comment]
I had the same issue under Debian. After I installed "libvirt-bin, libvirt-clients, libvirt-daemon and libvirt-daemon-system", works as well. How it will solve your issue also.

**Comment by yves-vogl** [comment]
This works for me:

virt-manager -c qemu+ssh://<unprivileged-user>@<fqdn>/system?socket=/var/run/libvirt/libvirt-sock

**Comment by n0clues** [comment]
> This works for me:
> virt-manager -c qemu+ssh://@/system?socket=/var/run/libvirt/libvirt-sock

@ghost: can you tell me how? I've installed libvirt with home-brew but I still receive connection error.  Probably libvirtd doesn't run but I'm not sure how to start it. The error:

`$ virsh -c qemu+ssh://@/system?socket=/var/run/libvirt/libvirt-sock`
`error: failed to connect to the hypervisor`
`error: internal error: received hangup event on socket`

**Comment by psychemedia** [comment]
I'm stuck too... running:

```/usr/local/sbin/libvirtd -d```

seems to start a daemon but it doesn't write anything to eg `/var/run/libvirt/libvirt-sock` which is where I'm guessing is the previous hints suggest a connection file might appear?

**Comment by aristofanio** [comment]
For me work with: ```virt-manager -c qemu:///session?socket=/Users/arigarcia/.cache/libvirt/libvirt-sock```

**Comment by sideeffect42** [comment]
I just figured out that this error can also occur if the remote host is e.g. running Debian and has an implementation of `nc` which does not support the `-U` option.

On the Mac the error is suppressed. When connecting from a GNU/Linux machine I got this error:
```
error: failed to connect to the hypervisor
error: End of file while reading data: nc: invalid option -- 'U'
nc -h for help: Input/output error
```

In this case the fix is to install `netcat-openbsd` on the remote machine.
I hope that this hint is of help to someone else, too.

**Comment by yulgang-labs** [comment]
> > This works for me:
> > virt-manager -c qemu+ssh://@/system?socket=/var/run/libvirt/libvirt-sock
> 
> @ghost: can you tell me how? I've installed libvirt with home-brew but I still receive connection error. Probably libvirtd doesn't run but I'm not sure how to start it. The error:
> 
> `$ virsh -c qemu+ssh://@/system?socket=/var/run/libvirt/libvirt-sock`
> `error: failed to connect to the hypervisor`
> `error: internal error: received hangup event on socket`

=====================
this works for my home-brew virt-manager:
virt-manager -c qemu+ssh://username@host:port/system?socket=/var/run/libvirt/libvirt-sock


thanks @ghost
