### ISSUE TITLE
El Capitan fresh install trouble

### ISSUE THREAD

**Issue by gulbinas** [jeffreywildman/homebrew-virt-manager#28]
```
[xxxxxxx@mac-os ~]$ brew install virt-manager virt-viewer
==> Installing virt-manager from jeffreywildman/homebrew-virt-manager
==> Installing dependencies for jeffreywildman/virt-manager/virt-manager: libsoup-with-gnome
==> Installing jeffreywildman/virt-manager/virt-manager dependency: libsoup-with-gnome
==> Downloading https://download.gnome.org/sources/libsoup/2.52/libsoup-2.52.0.tar.xz
Already downloaded: /Library/Caches/Homebrew/libsoup-with-gnome-2.52.0.tar.xz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/libsoup-with-gnome/2.52.0 --disable-tls-check
==> make install
🍺  /usr/local/Cellar/libsoup-with-gnome/2.52.0: 195 files, 5.5M, built in 29 seconds
==> Installing jeffreywildman/virt-manager/virt-manager
==> Downloading https://virt-manager.org/download/sources/virt-manager/virt-manager-1.2.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/virt-manager-1.2.1.tar.gz
==> Patching
patching file virt-clone
patching file virt-convert
patching file virt-install
patching file virt-manager
patching file virt-xml
==> Downloading https://libvirt.org/sources/python/libvirt-python-1.2.19.tar.gz
Already downloaded: /Library/Caches/Homebrew/virt-manager--libvirt-python-1.2.19.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/virt-manager/1.2.1/libexec/vendor --single-version-externally-managed --record=installed.txt
Last 15 lines from /Users/justinas/Library/Logs/Homebrew/virt-manager/01.python:
Traceback (most recent call last):
  File "generator.py", line 2126, in <module>
    if buildStubs(sys.argv[1], sys.argv[2]) < 0:
  File "generator.py", line 887, in buildStubs
    parser.feed(data)
  File "/usr/local/lib/python2.7/site-packages/_xmlplus/sax/expatreader.py", line 216, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/local/lib/python2.7/site-packages/_xmlplus/sax/expatreader.py", line 312, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "generator.py", line 139, in start
    if "string" in attrs:
  File "/usr/local/lib/python2.7/site-packages/_xmlplus/sax/xmlreader.py", line 316, in __getitem__
    return self._attrs[name]
KeyError: 0
error: command '/usr/local/opt/python/bin/python2.7' failed with exit status 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/jeffreywildman/homebrew-virt-manager/issues
```

**Comment by jeffreywildman** [comment]
After upgrading to El Capitan (10.11.1), I'm unable to reproduce the above error, even after uninstalling all homebrew formulae.  However, I did install the homebrewed python prior to re-installing virt-manager.

**Comment by jeffreywildman** [comment]
Closed due to inactivity.  Feel free to reopen if new information is available.
