### ISSUE TITLE
Error: undefined method `desc' for VirtManager:Class

### ISSUE THREAD

**Issue by zminds** [jeffreywildman/homebrew-virt-manager#38]
```sh
Error: undefined method `desc' for VirtManager:Class
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Taps/jeffreywildman/homebrew-virt-manager/virt-manager.rb:2:in `<class:VirtManager>'
/usr/local/Library/Taps/jeffreywildman/homebrew-virt-manager/virt-manager.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/formulary.rb:77:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:63:in `klass'
/usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:185:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:42:in `install'
/usr/local/Library/brew.rb:136:in `<main>'
```

**Comment by adenau** [comment]
Just run a `brew update` and you will be fine. Apparently the method was added recently.

**Comment by jeffreywildman** [comment]
Any status update on this issue? Will close if resolved or no additional information to act on.

**Comment by zminds** [comment]
OK I have installed done
Thank all
