### ISSUE TITLE
Unable to connect to remote session via SSH

### ISSUE THREAD

**Issue by PrestonL** [jeffreywildman/homebrew-virt-manager#46]
I tried launching virt-manager with the "--debug" and "--no-fork" flags, and am able to SSH into the remote machine via CLI using my public-private keys via "ssh root@192.168.1.140"  I have tried with root and my local user account on the remote system.  No matter what, I always get this error:

Libvirt URI is: qemu+ssh://root@192.168.1.140/system

Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/1.3.2/libexec/share/virt-manager/virtManager/connection.py", line 903, in _do_open
    self._backend.open(self._do_creds_password)
  File "/usr/local/Cellar/virt-manager/1.3.2/libexec/share/virt-manager/virtinst/connection.py", line 148, in open
    open_flags)
  File "/usr/local/Cellar/virt-manager/1.3.2/libexec/vendor/lib/python2.7/site-packages/libvirt.py", line 105, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirtError: An error occurred, but the cause is unknown

**Comment by PrestonL** [comment]
Closing, was able to connect with this:
virt-manager -c qemu+ssh://user@libvirthost/system?socket=/var/run/libvirt/libvirt-sock
