### ISSUE TITLE
Unable to connect to libvirt

### ISSUE THREAD

**Issue by onastvar** [jeffreywildman/homebrew-virt-manager#63]
Anyone know how to fix **libvirt issue**. I'm on El Capitan. All installed fine.

Unable to connect to libvirt.

An error occurred, but the cause is unknown

Verify that the 'libvirtd' daemon is running
on the remote host.

Libvirt URI is: qemu+ssh://root@server/system?socket=/var/run/libvirt/libvirt-sock

Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/1.4.0/libexec/share/virt-manager/virtManager/connection.py", line 904, in _do_open
    self._backend.open(self._do_creds_password)
  File "/usr/local/Cellar/virt-manager/1.4.0/libexec/share/virt-manager/virtinst/connection.py", line 148, in open
    open_flags)
  File "/usr/local/Cellar/virt-manager/1.4.0/libexec/vendor/lib/python2.7/site-packages/libvirt.py", line 105, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')_
libvirtError: An error occurred, but the cause is unknown

**Comment by skshandilya** [comment]
any workarounds for this? I am connecting from 1.4 virt-manager to libvirt version 1.3.1

**Comment by btro** [comment]
I receive the same error like OP. My virt-manager --version: 1.4.0. Mac OS: 10.12.2 (16C67). My Linux machine can connect via the URI without any problem. I'm using public key auth and no password prompt is happening or is expected - maybe that is related?

```
[Sun, 25 Dec 2016 23:17:26 virt-manager 81838] DEBUG (engine:140) Initial gtkapplication activated
[Sun, 25 Dec 2016 23:17:26 virt-manager 81838] DEBUG (connection:569) conn=qemu+ssh://user@[IP]/system changed to state=Connecting
[Sun, 25 Dec 2016 23:17:26 virt-manager 81838] DEBUG (connection:888) Scheduling background open thread for qemu+ssh://user@[IP]/system
[Sun, 25 Dec 2016 23:17:27 virt-manager 81838] DEBUG (connection:569) conn=qemu+ssh://user@[IP]/system changed to state=Disconnected
[Sun, 25 Dec 2016 23:17:27 virt-manager 81838] DEBUG (engine:638) connect_error: conn transport=ssh
[Sun, 25 Dec 2016 23:17:27 virt-manager 81838] DEBUG (error:99) error dialog message:
summary=Unable to connect to libvirt.

An error occurred, but the cause is unknown

Verify that the 'libvirtd' daemon is running
on the remote host.
details=Unable to connect to libvirt.

An error occurred, but the cause is unknown
[...]
```
No workaround on my end :(

**Comment by yanyao** [comment]
Looks like the same issue:

``` bash
yanyao@localhost:~|⇒  virsh -c qemu+ssh://root@192.168.100.107/system
error: failed to connect to the hypervisor
error: An error occurred, but the cause is unknown
```

**Comment by alv000h** [comment]
+1
Same here

Libvirt URI is: qemu+ssh://user@marte/system?socket=/var/run/libvirt/libvirt-sock

Traceback (most recent call last):
File "/usr/local/Cellar/virt-manager/1.4.0/libexec/share/virt-manager/virtManager/connection.py", line 904, in _do_open
self._backend.open(self._do_creds_password)
File "/usr/local/Cellar/virt-manager/1.4.0/libexec/share/virt-manager/virtinst/connection.py", line 148, in open
open_flags)
File "/usr/local/Cellar/virt-manager/1.4.0/libexec/vendor/lib/python2.7/site-packages/libvirt.py", line 105, in openAuth
if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirtError: An error occurred, but the cause is unknown

**Comment by Caseraw** [comment]
Yeah, same here.
Looking forward to a solution.

**Comment by alv000h** [comment]
@jeffreywildman any idea on this error?

**Comment by TheFonix** [comment]
Meanwhile we still wait :(

**Comment by dakwak** [comment]
i have been getting the same error all the way. Then I decided to use the socket in the connection URI. virt-manager --no-fork -c qemu+ssh://root@libvirthost/system?socket=/run/libvirt/libvirt-sock  
in your case libvirt-sock can be somewhere else on the host, try to locate it. that should make a successful connection

**Comment by kaishh** [comment]
This worked `virt-manager -c 'qemu+ssh://user@host/session?socket=/var/run/libvirt/libvirt-sock'`

**Comment by aristofanio** [comment]
This worked:  ```virt-manager -c 'qemu:///session'``` (based in @kaishh )

**Comment by xBitsSec** [comment]
Hello guys!

I had the same problem. Login not possible with correct string and `socket` parameter.
Daemon is running on server site, local check on server side of the hypervisor with `virsh` was successfull, but, the connection had always the error `received hangup event on socket`.

I searched all of threats, nothing worked. Simple idea at last - setup a VirtualBox machine with the same OS as the server :) Now, i found the bug!

This was a incompatible package of `netcat`!
It is important, to use the `openbsd netcat` package on your server side!

I changed it to the `openbsd netcat` package and, voilà, connection is working on macOS Mojave 10.14.4 :)

![VirtManagerConnectionMacOsMojave](https://user-images.githubusercontent.com/27640321/56409645-51d5a980-627a-11e9-8e07-33213b4e9fd4.jpg)

**Comment by karpulix** [comment]
> This worked `virt-manager -c 'qemu+ssh://user@host/session?socket=/var/run/libvirt/libvirt-sock'` with ssh keys auth

Thank you, this worked!

**Comment by bhundven** [comment]
On 15.2 here. I also had to install xquartz, then run a terminal from xquartz. In the xquartz terminal run:
```
virt-manager -c "qemu:///session" --no-fork
```
I haven't had a stable experience running virt-manager on MacOS. I have both a UTM linux vm and another laptop running linux, and usually use virsh or virt-manager with the following connection string:
```
"qemu+ssh://<username>@<ip_address_of_mac>/session?socket=/Users/<username>/.cache/libvirt/libvirt-sock"
```
or just virsh locally on macos with the same from above:
```
"qemu:///session"
```
