### ISSUE TITLE
gi has no attribute 'require_version'

### ISSUE THREAD

**Issue by matandobr** [jeffreywildman/homebrew-virt-manager#74]
installed on my mac sierra 10.12.5 without errors, but getting this issue:

MacBook-Pro-2:repos matandobr$ virt-manager
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/1.4.1/libexec/share/virt-manager/virt-manager", line 30, in <module>
    gi.require_version('LibvirtGLib', '1.0')
AttributeError: 'module' object has no attribute 'require_version'

I googled it, there are a lot of answers but none of them did the trick. help?

**Comment by MoritzFago** [comment]
look at my issue #76, that worked for me

**Comment by matandobr** [comment]
I did what @MoritzFago wrote, It started and then the python crushed, It's now working only with the --debug flag, that is strange.

**Comment by jpantsjoha** [comment]
im seeing the same issue on my new brew install(fresh build) --debug or not, it spits errors

> Traceback (most recent call last):
>   File "/usr/local/Cellar/virt-manager/1.4.1/libexec/share/virt-manager/virt-manager", line 30, in <module>
>     gi.require_version('LibvirtGLib', '1.0')
> AttributeError: 'module' object has no attribute 'require_version'
