### ISSUE TITLE
Installing failed with "ImportError: No module named setuptools"

### ISSUE THREAD

**Issue by zh-f** [jeffreywildman/homebrew-virt-manager#95]
While installing virt-manager and virt-viewer using `brew install virt-manager virt-viewer`, I met this error and had no clue how to solve it:
```
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/virt-manager--homebrew-virtualenv-20180423-3468-1n725f2/target --single-version-externally-managed --record=installed.txt
Last 15 lines from /Users/ZH.F/Library/Logs/Homebrew/virt-manager/01.python:
python
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/tmp/virt-manager--homebrew-virtualenv-20180423-3468-1n725f2/target
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named setuptools

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62
```
Could somebody help me out here?

**Comment by ckleu** [comment]
I got this same exact error - been playing around adding/removing different packages.. but no luck so far to get my virt-manager up-and-running  again :(

**Comment by dents** [comment]
Also having this problem when trying to do a fresh install.

**Comment by ckleu** [comment]
I got it working, but I didn't make the best kind of notes :( pasting some of them below

```
brew reinstall python@2
pip3 install --upgrade pip setuptools wheel
pip install --upgrade pip setuptools wheel
brew install virt-manager virt-viewer
brew install pygobject3 --with-python@2 gtk+3
brew reinstall pygobject3
brew reinstall gtk+3
```

**Comment by dents** [comment]
`brew reinstall python@2
pip3 install --upgrade pip setuptools wheel`
Did the trick for me.

**Comment by zh-f** [comment]
Thanks @ckleu @dents , but unfortunately, I tried to reinstall but got no lucky result.
```shell
==> Reinstalling jeffreywildman/virt-manager/virt-manager
==> Downloading https://virt-manager.org/download/sources/virt-manager/virt-manager-1.5.1.tar.gz
Already downloaded: /Users/ZH.F/Library/Caches/Homebrew/virt-manager-1.5.1.tar.gz
==> Patching
patching file virt-manager
==> Downloading https://files.pythonhosted.org/packages/33/bc/fa0b5347139cd9564f0d44ebd2b147ac97c36b2403943dbee8a25fd74012/virtualenv-16.0.0.tar.gz
Already downloaded: /Users/ZH.F/Library/Caches/Homebrew/virt-manager--homebrew-virtualenv-16.0.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/virt-manager--homebrew-virtualenv-20180608-16965-12l2jyk/target --single-version-externally-managed --record=installed.txt
==> python -s /tmp/virt-manager--homebrew-virtualenv-20180608-16965-12l2jyk/target/bin/virtualenv -p python /usr/local/Cellar/virt-manager/1.5.1/libexec
==> Downloading https://libvirt.org/sources/python/libvirt-python-2.3.0.tar.gz
Already downloaded: /Users/ZH.F/Library/Caches/Homebrew/virt-manager--libvirt-python-2.3.0.tar.gz
==> /usr/local/Cellar/virt-manager/1.5.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/virt-manager--libvirt-python-20180608-16965-155b12f/libvirt-python-2.3.0
Last 15 lines from /Users/ZH.F/Library/Logs/Homebrew/virt-manager/03.pip:
  Removing source in /private/tmp/pip-req-build-j3dwMm
Command "/usr/local/Cellar/virt-manager/1.5.1/libexec/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-j3dwMm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-iJ14mn/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/1.5.1/libexec/bin/../include/site/python2.7/libvirt-python" failed with error code 1 in /private/tmp/pip-req-build-j3dwMm/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/1.5.1/libexec/lib/python2.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/virt-manager/1.5.1/libexec/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/usr/local/Cellar/virt-manager/1.5.1/libexec/lib/python2.7/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/local/Cellar/virt-manager/1.5.1/libexec/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 779, in install
    spinner=spinner,
  File "/usr/local/Cellar/virt-manager/1.5.1/libexec/lib/python2.7/site-packages/pip/_internal/utils/misc.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/local/Cellar/virt-manager/1.5.1/libexec/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-j3dwMm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-iJ14mn/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/1.5.1/libexec/bin/../include/site/python2.7/libvirt-python" failed with error code 1 in /private/tmp/pip-req-build-j3dwMm/

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
Crashing on install at /usr/local/Cellar/virt-manager/1.5.1/libexec/bin/pip install https://github.com/jeffreywildman/homebrew-virt-manager/issues/98
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62
```
😢

**Comment by mjiao** [comment]
@zh-f me too. I have the same issue.

**Comment by elproducto** [comment]
I can confirm that re-tapping does not resolve this issue.   Issue was resolved by  tweaking recommendation above but for Python 3 based on recent changed to this brew formula for Virt-Manager 2.0.0.  I typed the following to get Virt-manager and Virt-viewer installed. Not sure if it make a different but, I also want to add that I did use brew remove for Virt-manager and Virt-viewer  prior to running the following commands.

```
brew reinstall python@3
brew install virt-manager virt-viewer
```

**Comment by jeffreywildman** [comment]
Closing for older version of `virt-manager`, which is now at 2.2.1 and uses python3. Please re-open if still an issue with the latest formula.

**Comment by johnnydubrovnik** [comment]
Sorry to reopen, but got this same error today:

`==> Installing jeffreywildman/virt-manager/virt-manager
==> Patching
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/virt-manager--homebrew-virtualenv-20201104-79131-1y1nn1n/target/vendor -
Last 15 lines from /Users/jp/Library/Logs/Homebrew/virt-manager/01.python3:
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/private/tmp/virt-manager--homebrew-virtualenv-20201104-79131-1y1nn1n/target/vendor
--install-scripts=/private/tmp/virt-manager--homebrew-virtualenv-20201104-79131-1y1nn1n/target/vendor/bin
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'
`
