### ISSUE TITLE
Crashing on install at /usr/local/Cellar/virt-manager/1.5.1/libexec/bin/pip install

### ISSUE THREAD

**Issue by HowellBP** [jeffreywildman/homebrew-virt-manager#98]
```
Command "/usr/local/Cellar/virt-manager/1.5.1/libexec/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-8W9lkV/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-l8GEld/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/1.5.1/libexec/bin/../include/site/python2.7/libvirt-python" failed with error code 1 in /private/tmp/pip-req-build-8W9lkV/
```

Here's the whole error and install log. I already had some of the dependencies installed.
https://pastebin.com/EGZ3Qq15

I'm not sure exactly where the problem is. Is this a python conflict? Should I try uninstalling all of my homebrew python versions?

**Comment by HowellBP** [comment]
Side note, I tried going to the location of the code in question, but since brew does cleanup, the /usr/local/Cellar/virt-manager directory gets deleted after things blow up.

**Comment by HowellBP** [comment]
Confirmed that updating libvirt-python to 4.4.0 solves the issue. I modified virt-manager.rb with the new versionand SHA256 and the install worked properly.

**Comment by RoniLevin** [comment]
I have the issue with char**, but for some reason the the libvirt being downloaded is 4.2.0 instead of 4.4.0.

```
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/virt-manager--homebrew-virtualenv-20180610-78181-q6nwrl/target --single-version-externally-managed --record=installed.txt
==> python -s /tmp/virt-manager--homebrew-virtualenv-20180610-78181-q6nwrl/target/bin/virtualenv -p python /usr/local/Cellar/virt-manager/1.5.1/libexec
==> Downloading https://libvirt.org/sources/python/libvirt-python-4.2.0.tar.gz
```

any idea why?

**Comment by sandalle** [comment]
I just installed this tap today and still have this issue, with the same note as @RoniLevin that it's still installing libvirt-python 4.2.0 instead of 4.4.0 as mentioned in https://github.com/renegaderyu/homebrew-virt-manager/commit/623e775e19de99d00e6c76bcde894fff8f5697e2 .
```
==> Downloading https://libvirt.org/sources/python/libvirt-python-4.2.0.tar.gz
Already downloaded: /Users/sandalle/Library/Caches/Homebrew/virt-manager--libvirt-python-4.2.0.tar.gz
==> /usr/local/Cellar/virt-manager/1.5.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /p
Last 15 lines from /Users/sandalle/Library/Logs/Homebrew/virt-manager/03.pip:
  Removing source in /private/tmp/pip-req-build-mGlmrE
Command "/usr/local/Cellar/virt-manager/1.5.1/libexec/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-mGlmrE/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-FPBHpQ/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/1.5.1/libexec/bin/../include/site/python2.7/libvirt-python" failed with error code 1 in /private/tmp/pip-req-build-mGlmrE/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/1.5.1/libexec/lib/python2.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/virt-manager/1.5.1/libexec/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/usr/local/Cellar/virt-manager/1.5.1/libexec/lib/python2.7/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/local/Cellar/virt-manager/1.5.1/libexec/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 779, in install
    spinner=spinner,
  File "/usr/local/Cellar/virt-manager/1.5.1/libexec/lib/python2.7/site-packages/pip/_internal/utils/misc.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/local/Cellar/virt-manager/1.5.1/libexec/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-mGlmrE/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-FPBHpQ/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/1.5.1/libexec/bin/../include/site/python2.7/libvirt-python" failed with error code 1 in /private/tmp/pip-req-build-mGlmrE/
```

When I check my local clone (cloned today) of https://github.com/jeffreywildman/homebrew-virt-manager , virt-manager.rb is only up to commit d35810cb3382e5ba9a5bbafdd10e27c9caccbe82 for refreshing to 4.2.0. If I run `brew edit virt-manager` and manually make the changes from https://github.com/renegaderyu/homebrew-virt-manager/commit/623e775e19de99d00e6c76bcde894fff8f5697e2 , installation works. :)

**Comment by RoniLevin** [comment]
I can confirm @sandalle solution fixed the problem. Thanks!

**Comment by odyssey4me** [comment]
Agreed, works like a charm! Thanks!

**Comment by falfaro** [comment]
Works like a charm for me too. Can we please merge renegaderyu/homebrew-virt-manager into master?

**Comment by jeffreywildman** [comment]
Merged, thanks!
